### ISSUE TITLE
LanguageClient: Not executable

### ISSUE THREAD

**Issue by FelipeMarcelino** [autozimu/LanguageClient-neovim#279] opened 2018-01-15 15:39 UTC
I try to use LanguaCleint-neovim with deoplete. But after install plugin, i have a error message:
LanguageClient: Not executable.

I have a bin file inside bin folder:
languageclient 0.1.27 (NULL 2018-01-15T15:34:24.041794872Z)
Nvim v0.2.2
Plugin Version: 72ce5b750368b95be58641ab591182fd859400dc

vimrc:

set hidden
let g:LanguageClient_devel = 1
let g:LanguageClient_loggingLevel = 'DEBUG'
let g:LanguageClient_serverCommands = {
  	\ 'python': ['python-language-server'],
 	\ }

let g:LanguageClient_selectionUI = 'location-list'

Log client:
2018-01-15T13:02:49.109949458-02:00 WARN languageclient::languageclient - No language server command found for type: vim.
2018-01-15T13:02:55.853378345-02:00 WARN languageclient::languageclient - Not opened yet. Switching to didOpen.

Log server: empty

**Comment by autozimu** [comment] 2018-01-15 22:34
Can you try start binary `bin/languageclient` directly from your shell?

**Comment by gavocanov** [comment] 2018-01-16 09:19
Same here in neovim, I can start it from the shell manually and it is executable.

It also does not work in Vim for the last few days, with your mini-vimrc opening a Rust file I'm getting:

```
LanguageClient caught exception: 'Vim(return):E906: not an open channel'
```

**Comment by FelipeMarcelino** [comment] 2018-01-16 13:49
Yes, i can execute binary from shell, but have the same result when I open nvim.

**Comment by ahmedelgabri** [comment] 2018-01-17 08:55
I have the same problem today after running `PlugUpdate` & it failed to run `./install.sh`

<img width="1086" alt="screen shot 2018-01-17 at 09 54 47" src="https://user-images.githubusercontent.com/63876/35033897-94151de2-fb6c-11e7-956e-4e5f6f5a13e9.png">

**Comment by Shougo** [comment] 2018-01-17 09:02
Hm.
It seems the download is failed.

The URI is correct in install.sh?

**Comment by ahmedelgabri** [comment] 2018-01-17 09:06
The URL is generated & seems to be right https://github.com/autozimu/LanguageClient-neovim/blob/next/install.sh#L25 but seems like no binaries? https://github.com/autozimu/LanguageClient-neovim/releases

**Comment by Shougo** [comment] 2018-01-17 09:10
It seems Yes.

**Comment by gavocanov** [comment] 2018-01-17 09:11
Today the download failed but the script then falls back to building it locally, and that's ok.
It builds without errors but I still get the same errors when starting both vim and neovim.

**Comment by ahmedelgabri** [comment] 2018-01-17 09:25
@gavocanov I think you need `cargo` for that, not everyone has `cargo` or even expects to have `cargo` installed if they install a vim plugin, right? :)

**Comment by gavocanov** [comment] 2018-01-17 10:03
sure, just sayin, for debug purposes ;)

**Comment by gavocanov** [comment] 2018-01-17 15:08
https://github.com/autozimu/LanguageClient-neovim/pull/285/files
this PR fixes it

**Comment by autozimu** [comment] 2018-01-17 15:37
Travis CI has some system issue hous/days ago. So the binary build was
delayed for quite a while.

Check travis CI status.

**Comment by autozimu** [comment] 2018-01-17 16:51
Please refrain from piggybacking similar but different issues within thread.

---
For the issue that this plugin stopped working for past several days, it was caused by a bad commit https://github.com/autozimu/LanguageClient-neovim/commit/ccec0c6e08cbe91ccce8652992de9f2011b5adfb and has been fixed in https://github.com/autozimu/LanguageClient-neovim/commit/dab664fe9cff0724834661723170167d589f0748.

---
For the 404 issue when downloading prebuilt binaries, it is a Travis CI issue, as explained above and also here https://github.com/autozimu/LanguageClient-neovim/issues/284.

---
This issue will solely for tracking the case that binary is downloaded but shows `Not executable!` error, quite possibly only for nvim.

**Comment by joaospinto** [comment] 2018-01-29 18:28
Everything was working fine for me until I ran `UpdateRemotePlugins` this morning, and now I get `LanguageClient: Not executable!` when I open nvim.

**Comment by ahmedelgabri** [comment] 2018-01-29 18:34
@joaospinto the installation changed a bit, check https://github.com/autozimu/LanguageClient-neovim/blob/next/README.md#quick-start

**Comment by joaospinto** [comment] 2018-01-29 18:39
That's exactly what I'm already doing, though. See my config file [here](https://gist.github.com/joaospinto/9ec0606a5a2456d542214f959fb6996d).

**Comment by ahmedelgabri** [comment] 2018-01-29 19:00
You mentioned `UpdateRemotePlugins` so I thought your config was not up to date because that's not needed anymore.

Your config looks fine, try removing the plugin, then run `UpdateRemotePlugins` to remove it from remote plugin list then install it again. also, another thing you could try is to replace `bash install.sh` with just `./install.sh`

**Comment by joaospinto** [comment] 2018-01-29 19:31
Absolutely, it was a reasonable assumption - I should have shared more details in my first comment, my apologies. Re-installing worked! :) Thanks

**Comment by autozimu** [comment] 2018-02-28 05:05
CI has been stable for some time. Closing.

**Closed by autozimu** 2018-02-28 05:05 UTC
