### ISSUE TITLE
language client cannot start

### ISSUE THREAD

**Issue by timfeirg** [autozimu/LanguageClient-neovim#958] opened 2020-01-21 06:21 UTC
- Did you upgrade to latest plugin version? yes
- Did you upgrade to/compile latest binary? yes
- (Neovim users only) Did you check output of `:checkhealth LanguageClient`? yes
- Did you check [troubleshooting]? yes

## Describe the bug

`:LanguageClientStart` results in an error, see debug logs below.

## Environment
- neovim/vim version (`nvim --version` or `vim --version`):

```
vi --version
NVIM v0.5.0-nightly-1538-g8ba3354d7
Build type: Release
LuaJIT 2.0.5
Compilation: /usr/local/Homebrew/Library/Homebrew/shims/mac/super/clang -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1 -DNDEBUG -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wshadow -Wconversion -Wmissing-prototypes -Wimplicit-fallthrough -Wvla -fstack-protector-strong -fdiagnostics-color=auto -DINCLUDE_GENERATED_DECLARATIONS -D_GNU_SOURCE -DNVIM_MSGPACK_HAS_FLOAT32 -DNVIM_UNIBI_HAS_VAR_FROM -DMIN_LOG_LEVEL=3 -I/tmp/neovim-20200116-74399-xim55y/build/config -I/tmp/neovim-20200116-74399-xim55y/src -I/usr/local/include -I/tmp/neovim-20200116-74399-xim55y/deps-build/include -I/usr/local/opt/gettext/include -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.15.sdk/usr/include -I/tmp/neovim-20200116-74399-xim55y/build/src/nvim/auto -I/tmp/neovim-20200116-74399-xim55y/build/include
Compiled by timfeirg@timfeirg-mba-7.local

Features: +acl +iconv +tui
See ":help feature-compile"

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/usr/local/Cellar/neovim/HEAD-8ba3354/share/nvim"

Run :checkhealth for more info
```

- This plugin version (`git rev-parse --short HEAD`): `fb02afed15363c8879277b413b89e6ca51589e6a`
- This plugin's binary version (`bin/languageclient --version`): `languageclient 0.1.156 fb02afed15363c8879277b413b89e6ca51589e6a`
- Minimal vimrc content (A minimal vimrc is the smallest vimrc that could
  reproduce the issue. Refer to an example [here][min-vimrc.vim]):

```
call plug#begin('~/.local/share/nvim/plugged')

Plug 'autozimu/LanguageClient-neovim', {
    \ 'branch': 'next',
    \ 'do': 'bash install.sh',
    \ }

call plug#end()

" Always draw sign column. Prevent buffer moving when adding/deleting sign.
set signcolumn=yes

let g:LanguageClient_serverCommands = {
            \ 'python': ['pyls'],
    \ }
let $LANGUAGECLIENT_DEBUG=1
let g:LanguageClient_loggingLevel='DEBUG'
let g:LanguageClient_autoStart=1

let g:LanguageClient_virtualTextPrefix = ''
let g:LanguageClient_loggingFile =  expand('~/.local/share/nvim/LanguageClient.log')
let g:LanguageClient_serverStderr = expand('~/.local/share/nvim/LanguageServer.log')
```

- Language server link and version:

[min-vimrc.vim]: https://github.com/autozimu/LanguageClient-neovim/blob/next/min-vimrc.vim

## To Reproduce

```
let $LANGUAGECLIENT_DEBUG=1
let g:LanguageClient_loggingLevel='DEBUG'
let g:LanguageClient_autoStart=0
```

Make a debug build by running

```
make build
```

And then open a file and run :LanguageClientStart. /tmp/LanguageClient.log and /tmp/LanguageServer.log should have detailed logs.

## Current behavior

I have followed steps in https://github.com/autozimu/LanguageClient-neovim/issues/208#issuecomment-353521892 to produce this debug log:

* /private/tmp/LanguageClient.log

```
#######
LanguageClient 0.1.156 fb02afed15363c8879277b413b89e6ca51589e6a
#######
13:55:19 DEBUG unnamed src/language_client.rs:65 state: null ==> {"autoStart":true,"capabilities":{},"change_throttle":null,"code_lens":{},"completionPreferTextEdit":false,"diagnostics":{},"diagnosticsDis
13:55:19 INFO writer-None src/rpcclient.rs:215 => None {"jsonrpc":"2.0","method":"eval","params":["[!!get(g:, 'LanguageClient_autoStart', 1), s:GetVar('LanguageClient_serverCommands', {}), get(g:, 'Langua
13:55:19 INFO reader-None src/rpcclient.rs:169 <= None {"id": 4, "jsonrpc": "2.0", "result": [0, {"c": ["cquery", "--log-file=/tmp/cq.log"], "go": ["go-langserver"], "cpp": ["cquery", "--log-file=/tmp/cq.
13:55:19 INFO writer-None src/rpcclient.rs:215 => None {"jsonrpc":"2.0","method":"eval","params":["[get(g:, 'LanguageClient_diagnosticsSignsMax', v:null), get(g:, 'LanguageClient_diagnosticsMaxSeverity',
13:55:19 INFO reader-None src/rpcclient.rs:169 <= None {"id": 5, "jsonrpc": "2.0", "result": [null, "Hint", {}, 1, 0, 1]}
13:55:19 ERROR unnamed src/rpchandler.rs:13 Error handling message: invalid type: integer `0`, expected string or map

Message: {"jsonrpc":"2.0","method":"languageClient/startServer","params":{"bufnr":1,"cmdargs":[],"filename":"/Users/timfeirg/ein/lain-cli/future_lain_cli/lain.py","languageId":"python"},"id":2}

Error: Error("invalid type: integer `0`, expected string or map", line: 0, column: 0)
13:55:19 INFO writer-None src/rpcclient.rs:215 => None {"jsonrpc":"2.0","error":{"code":-32603,"message":"invalid type: integer `0`, expected string or map"},"id":2}
```

* /private/tmp/LanguageServer.log

```
#######
LanguageClient 0.1.156 fb02afed15363c8879277b413b89e6ca51589e6a
#######
14:05:33 DEBUG unnamed src/language_client.rs:65 state: null ==> {"autoStart":true,"capabilities":{},"change_throttle":null,"code_lens":{},"completionPreferTextEdit":false,"diagnostics":{},"diagnosticsDisplay":{"1":{"name":"Error","signText":"✖","signTexthl":"ALEErrorSign","texthl":"ALEError","virtualTexthl":"Error"},"2":{"name":"Warning","signText":"⚠","signTexthl":"ALEWarningSign","texthl":"ALEWarning","virtualTexthl":"Todo"},"3":{"name":"Information","signText":"ℹ","signTexthl":"ALEInfoSign","texthl":"ALEInfo","virtualTexthl":"Todo"},"4":{"name":"Hint","signText":"➤","signTexthl":"ALEInfoSign","texthl":"ALEInfo","virtualTexthl":"Todo"}},"diagnosticsEnable":true,"diagnosticsList":"Quickfix","diagnosticsSignsMax":null,"diagnostics_max_severity":4,"documentHighlightDisplay":{"1":{"name":"Text","texthl":"SpellCap"},"2":{"name":"Read","texthl":"SpellLocal"},"3":{"name":"Write","texthl":"SpellRare"}},"document_highlight_source":null,"echo_project_root":true,"highlight_match_ids":[],"highlight_source":null,"highlights":{},"highlights_placed":{},"hoverPreview":"Auto","is_nvim":false,"last_cursor_line":0,"last_line_diagnostic":" ","loadSettings":false,"loggingFile":null,"loggingLevel":"WARN","namespace_id":null,"registrations":[],"rootMarkers":null,"roots":{},"selectionUI":"LocationList","selectionUI_autoOpen":true,"serverCommands":{},"serverStderr":null,"settingsPath":".vim/settings.json","sign_next_id":75000,"signs":{},"stashed_codeAction_actions":[],"text_documents":{},"text_documents_metadata":{},"trace":null,"use_virtual_text":"All","user_handlers":{},"wait_output_timeout":{"nanos":0,"secs":10},"windowLogMessageLevel":2}
14:05:33 INFO writer-None src/rpcclient.rs:215 => None {"jsonrpc":"2.0","method":"eval","params":["[!!get(g:, 'LanguageClient_autoStart', 1), s:GetVar('LanguageClient_serverCommands', {}), get(g:, 'LanguageClient_selectionUI', v:null), get(g:, 'LanguageClient_trace', v:null), expand(get(g:, 'LanguageClient_settingsPath', '.vim/settings.json')), !!get(g:, 'LanguageClient_loadSettings', 1), get(g:, 'LanguageClient_rootMarkers', v:null), get(g:, 'LanguageClient_changeThrottle', v:null), get(g:, 'LanguageClient_waitOutputTimeout', v:null), !!get(g:, 'LanguageClient_diagnosticsEnable', 1), get(g:, 'LanguageClient_diagnosticsList', 'Quickfix'), get(g:, 'LanguageClient_diagnosticsDisplay', {}), get(g:, 'LanguageClient_windowLogMessageLevel', 'Warning'), get(g:, 'LanguageClient_hoverPreview', 'Auto'), get(g:, 'LanguageClient_completionPreferTextEdit', 0), has('nvim')]"],"id":3}
14:05:33 INFO reader-None src/rpcclient.rs:169 <= None {"id": 3, "jsonrpc": "2.0", "result": [1, {"c": ["cquery", "--log-file=/tmp/cq.log"], "go": ["go-langserver"], "cpp": ["cquery", "--log-file=/tmp/cq.log"], "vue": ["vls"], "lua": ["lua-lsp"], "sh": ["bash-language-server", "start"], "dockerfile": ["docker-langserver", "--stdio"], "html": ["html-languageserver", "--stdio"], "dart": ["dart", "/usr/local/opt/dart/libexec/bin/snapshots/analysis_server.dart.snapshot", "--lsp"], "css": ["css-languageserver", "--stdio"], "python": ["pyls"]}, null, null, ".vim/settings.json", 1, null, null, null, 1, "Disabled", {}, "Warning", "Auto", 0, 1]}
14:05:33 INFO writer-None src/rpcclient.rs:215 => None {"jsonrpc":"2.0","method":"eval","params":["[get(g:, 'LanguageClient_diagnosticsSignsMax', v:null), get(g:, 'LanguageClient_diagnosticsMaxSeverity', 'Hint'), get(g:, 'LanguageClient_documentHighlightDisplay', {}), !!s:GetVar('LanguageClient_selectionUI_autoOpen', 1), s:useVirtualText(), !!s:GetVar('LanguageClient_echoProjectRoot', 1)]"],"id":4}
14:05:33 INFO reader-None src/rpcclient.rs:169 <= None {"id": 4, "jsonrpc": "2.0", "result": [null, "Hint", {}, 1, 0, 1]}
14:05:33 WARN unnamed src/language_server_protocol.rs:2416 Failed to start language server automatically. invalid type: integer `0`, expected string or map
14:05:33 INFO unnamed src/language_server_protocol.rs:2421 End languageClient/handleFileType
14:05:36 INFO reader-None src/rpcclient.rs:169 <= None {"method": "exit", "jsonrpc": "2.0", "params": {"bufnr": 1, "languageId": "log"}}
14:05:36 INFO unnamed src/language_server_protocol.rs:2245 Begin exit
14:05:36 INFO writer-None src/rpcclient.rs:215 => None {"jsonrpc":"2.0","method":"eval","params":["LSP#filename()"],"id":5}
14:05:36 INFO reader-None src/rpcclient.rs:169 <= None {"id": 5, "jsonrpc": "2.0", "result": "/private/tmp/LanguageClient.log"}
14:05:36 INFO reader-None src/rpcclient.rs:202 reader-None terminated
```

**Comment by bnjbvr** [comment] 2020-01-31 14:42
Could it be a duplicate of and fixed by https://github.com/autozimu/LanguageClient-neovim/issues/947#issuecomment-572111189?

**Closed as completed** 2020-02-02 08:44 UTC
