### ISSUE TITLE
[Bug] 'Duplicate Identifier' when typing out the class

### ISSUE THREAD

**Issue by dylan-chong** [autozimu/LanguageClient-neovim#592] opened 2018-09-01 23:30 UTC
- Did you upgrade to latest plugin version? Yes
- Did you upgrade to/compile latest binary? Run shell command 
  `bin/languageclient --version` to get its version number. languageclient 0.1.114 542203b6aa435b93a21e123b2177b18cd1a1a8ed
- (Neovim users only) Did you check output of `:checkhealth LanguageClient`? Yes everything is fine
- Did you check [troubleshooting]?

[troubleshooting]: https://github.com/autozimu/LanguageClient-neovim/blob/next/INSTALL.md#6-troubleshooting

## Describe the bu

Vim buffer may not properly be created when jumping to the definition of the file. This causes the buffer not be shown in the airline tab line

## Environment
- neovim/vim version (`nvim --version` or `vim --version`): NVIM v0.3.1
- This plugin version (`git rev-parse --short HEAD`): 891ee2c
- This plugin's binary version (`bin/languageclient --version`): languageclient 0.1.114 542203b6aa435b93a21e123b2177b18cd1a1a8ed
- Minimal vimrc content (A minimal vimrc is the smallest vimrc that could
  reproduce the issue. Refer to an example [here][min-vimrc.vim]):
```
call plug#begin('~/.vim/plugged')

Plug 'autozimu/LanguageClient-neovim', {
    \ 'branch': 'next',
    \ 'do': 'bash install.sh',
    \ }
Plug 'vim-airline/vim-airline'

call plug#end()

augroup filetype_rust
    autocmd!
    autocmd BufReadPost *.rs setlocal filetype=rust
augroup END

" Always draw sign column. Prevent buffer moving when adding/deleting sign.
set signcolumn=yes

let g:LanguageClient_serverCommands = {
    \ 'rust': ['rustup', 'run', 'stable', 'rls'],
    \ 'typescript': ['typescript-language-server', '--stdio'],
    \ }
let $RUST_BACKTRACE = 1
let g:LanguageClient_loggingLevel = 'INFO'
let g:LanguageClient_loggingFile = stdpath('data') . '/LanguageClient.log'
let g:LanguageClient_serverStderr = stdpath('data') . '/LanguageServer.log'

au BufRead,BufNewFile *.ts set filetype=typescript

let g:airline#extensions#tabline#enabled = 1

```
- Language server link and version: https://github.com/theia-ide/typescript-language-server/releases/tag/v0.2.0

[min-vimrc.vim]: https://github.com/autozimu/LanguageClient-neovim/blob/next/min-vimrc.vim

## To Reproduce
1. clone `https://github.com/dylan-chong/prioritask`
1. `yarn install` or `npm install`
1. start vim with `nvim src/app/main.ts -u .vimrc`
1. physically type out the following code at the bottom of the file (yes physically, i believe timing is related to the bug)
```
class A {

}
```
1. press escape

## Current behavior

the gutter will show an error saying duplicate identifier

## Expected behavior

the error should not show

## Screenshots

Error: 
<img width="675" alt="screen shot 2018-09-02 at 11 16 37 am" src="https://user-images.githubusercontent.com/17482349/44950658-cc93b500-aea1-11e8-80aa-83812f30dbb0.png">

**Comment by stroiman** [comment] 2018-10-04 15:06
I'm experiencing this too, and also a few other error messages, for example "A module cannot have multiple default exports.". 

But they generally seem like the language server is receiving/parsing the file contents multiple times.

Though I never figured out if it's the neovim language client, or the typescript language server.

**Comment by stroiman** [comment] 2018-10-04 15:08
Have this in my `init.vim`, so when I do get the error messages, I can easily restart the language client 😁 

```
nnoremap <leader>lr :LanguageClientStop<cr>:LanguageClientStart<cr>
```

**Comment by martskins** [comment] 2020-11-08 11:34
The repo linked in the steps to reproduce is no longer accessible. I tried to reproduce this with a blank project and I couldn't reproduce the issue. Considering that there have been a lot of releases since this was reported and that the steps to reproduce are no longer valid, I'm closing this, but please re-open if this is still an issue for any of you.

**Closed as completed by martskins** 2020-11-08 11:34 UTC
