### ISSUE TITLE
Cannot display FZF preview window

### ISSUE THREAD

**Issue by ojroques** [autozimu/LanguageClient-neovim#969] opened 2020-02-02 18:10 UTC
- Did you upgrade to latest plugin version? **Yes**
- Did you upgrade to/compile latest binary? Run shell command
  `bin/languageclient --version` to get its version number. **Yes**
- (Neovim users only) Did you check output of `:checkhealth LanguageClient`? **Yes**
- Did you check [troubleshooting]? **Yes**

## Describe the bug
I would like to use the preview feature that FZF has, when looking for references of a symbol for instance. When I'm using FZF independently of languageclient-neovim, a window displays the context on the right side of the results (see screenshot below).

Issue #249 requested the feature but I just can't get it to work. I'm using the option `let g:LanguageClient_fzfOptions` introduced in this issue and I'm following the [example I've found in the source code](https://github.com/autozimu/LanguageClient-neovim/blob/543a88ab9ca2f4211d5df4f9bc9b19425c466374/autoload/LanguageClient.vim#L213) to set a value, but I systematically get an error message (see below).

## Environment
- neovim/vim version (`nvim --version` or `vim --version`): `0.4.3`
- This plugin version (`git rev-parse --short HEAD`): `543a88a`
- This plugin's binary version (`bin/languageclient --version`): `languageclient 0.1.156` 
- Minimal vimrc content (A minimal vimrc is the smallest vimrc that could
  reproduce the issue. Refer to an example [here][min-vimrc.vim]):

```
call plug#begin()
Plug 'autozimu/LanguageClient-neovim', {'branch': 'next', 'do': 'bash install.sh'}
Plug 'junegunn/fzf', {'dir': '~/.fzf', 'do': './install --all'}
Plug 'junegunn/fzf.vim'
call plug#end()

augroup filetype_rust
    autocmd!
    autocmd BufReadPost *.rs setlocal filetype=rust
augroup END

set signcolumn=yes

let g:LanguageClient_serverCommands = {
    \ 'rust': ['rustup', 'run', 'stable', 'rls'],
    \ 'python': ['pyls'],
    \ }

let $RUST_BACKTRACE = 1
let g:LanguageClient_fzfOptions = fzf#vim#with_preview().options
let g:LanguageClient_loggingLevel = 'INFO'
let g:LanguageClient_virtualTextPrefix = ''
let g:LanguageClient_loggingFile =  expand('~/.local/share/nvim/LanguageClient.log')
let g:LanguageClient_serverStderr = expand('~/.local/share/nvim/LanguageServer.log')

nnoremap <leader>r :call LanguageClient#textDocument_references()<CR>
```
- Language server link and version: None

[min-vimrc.vim]: https://github.com/autozimu/LanguageClient-neovim/blob/next/min-vimrc.vim

## To Reproduce
1. Run any file with the above configuration

## Current behavior
I get the error message:
```
Error detected while processing function fzf#vim#with_preview:
line   22:
E117: Unknown function: fzf#shellescape
E15: Invalid expression: ['--preview-window', window, '--preview', (s:is_win ? s:bin.preview : fzf#shellescape(s:bin.preview)).' {}']
line   27:
E121: Undefined variable: preview
E116: Invalid arguments for function <SNR>10_merge_opts
Error detected while processing /home/olivier/.vimrc:
line   20:
E716: Key not present in Dictionary: options
E15: Invalid expression: fzf#vim#with_preview().options
```

## Expected behavior
FZF preview would be available when languageclient-neovim lists the results of a command. Ideally like this:

![image](https://user-images.githubusercontent.com/23409060/73612875-bb475e80-45e7-11ea-8274-b770705fd868.png)

**Comment by harshasrisri** [comment] 2020-06-11 05:29
It seems to me that this problem occurs when there were no fzf.vim configurations. I had this same problem until a week ago and had disabled it. However, in the past week, I added some fzf configuration options. Adding back the line `let g:LanguageClient_fzfOptions = fzf#vim#with_preview().options` seems to have picked up the fzf.vim options and work without throwing any errors.

**Comment by ojroques** [comment] 2020-06-11 08:38
What do you mean "no fzf.vim configuration"? Would you mind sharing the relevant config parts to make it work?

**Comment by harshasrisri** [comment] 2020-06-23 05:50
Please excuse me for the delay. I added some configurations for fzf.vim to be used for :Files or :Rg etc., like, say:
```
let $FZF_DEFAULT_OPTS="--preview=bat --reverse"
```
Adding this causes LanguageClient to generates a view like the expected behavior picture you posted.

**Comment by ojroques** [comment] 2020-09-16 20:32
It did not work for me unfortunately. `fzf#vim#with_preview().options` is still broken. I'm using this workaround in the meantime (I'm using neovim):

```vim
let g:LanguageClient_fzfOptions = [
      \ '--delimiter', ':', '--preview-window', '+{2}-6',
      \ '--preview', '~/.config/nvim/plugged/fzf.vim/bin/preview.sh {}'
      \ ]
```

Obviously not great since the path to `preview.sh` must be manually set.

**Comment by martskins** [comment] 2020-10-17 12:33
@ojroques I'm seeing the same issue now. It seems like this is an issue because by the time that function call is evaluated the plugin hasn't been loaded yet (because of how vim-plug works). What I ended up doing to fix it was moving that bit of config to an autocmd so it's set after LanguageClient-neovim has started. 

So something like this fixes it: 

`autocmd User LanguageClientStarted let g:LanguageClient_fzfOptions = fzf#vim#with_preview().options`

Closing this issue now, but feel free to reopen if you want to discuss this further.

**Closed as completed by martskins** 2020-10-17 12:33 UTC

**Comment by harshasrisri** [comment] 2020-10-19 19:24
@martskins I used your solution to https://github.com/autozimu/LanguageClient-neovim/issues/1095 and combined it with `g:LanguageClient_selectionUI` to delegate the preview handling entirely to FZF by using:

```diff
+ let $FZF_DEFAULT_OPTS = "--delimiter ':' --preview-window '+{2}-20'"

+ function! LcnFzfSelectionUI(source, sink) abort
+     return fzf#run(fzf#wrap(fzf#vim#with_preview({'source': a:source, 'sink': a:sink})))
+ endfunction

- let g:LanguageClient_fzfOptions = fzf#vim#with_preview().options
+ let g:LanguageClient_selectionUI = function('LcnFzfSelectionUI')
```

This works like a charm and fixes another issue that I was seeing as well. 
(The other issue was that the LCN menu was showing up in quickfix window and not in FZF)
