### ISSUE TITLE
How to show hover information for selection?

### ISSUE THREAD

**Issue by srghma** [autozimu/LanguageClient-neovim#539] opened 2018-07-29 15:49 UTC
## Summary

on https://github.com/srghma/nixfromnpm/commit/cdb3cf5f25c549d9cb30cb6e8e84bc3c5081ce2e

Using `nix-shell --command 'code'` to start vscode and hovering on selection

![2018-07-29-18 44 26-screenshot](https://user-images.githubusercontent.com/7573215/43368052-7829f702-935f-11e8-815a-0e9f883302e9.png)

results in two type infos: one for `tagMap` (above) and second for selection `H.lookup tag tagMap` (below)

I can't reproduce the same on neovim

`nix-shell --command 'nvim'`

![2018-07-29-18 46 58-screenshot](https://user-images.githubusercontent.com/7573215/43368078-d26f6468-935f-11e8-8b31-b0ff718340f2.png)
![2018-07-29-18 47 01-screenshot](https://user-images.githubusercontent.com/7573215/43368079-d2b577aa-935f-11e8-8ecc-4c08ad8e551d.png)

What it actually shows is type of 

```hs
      case H.lookup tag tagMap of
        Just sha -> return sha
        Nothing -> throw (InvalidGitRef ref)
```

## Reproduction
- neovim/vim version (`nvim --version` or `vim --version`):

```
[nix-shell:~/projects/nixfromnpm]$ nvim --version
NVIM v0.2.2
Build type: Release
LuaJIT 2.1.0-beta3
Compilation: /nix/store/gqg2vrcq7krqi9rrl6pphvsg81sb8pjw-gcc-wrapper-7.3.0/bin/gcc -Wconversion -DNVIM_MSGPACK_HAS_FLOAT32 -DNVIM_UNIBI_HAS_VAR_FROM -O2 -DNDEBUG -DMIN_LOG_LEVEL=3 -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wimplicit-fallthrough -Wvla -fstack-protector-strong -fdiagnostics-color=auto -DINCLUDE_GENERATED_DECLARATIONS -D_GNU_SOURCE -I/build/source/build/config -I/build/source/src -I/nix/store/f45rl4z9a2rqd7hdhwnj9g831z1k4ilr-libuv-1.19.2/include -I/nix/store/amxxzxi8kwsk0ncbax64lyziaf49x12m-libmsgpack-2.1.5/include -I/nix/store/5caqy8vrrk3r6dg1j7is8hyjbyafxyrr-unibilium-2.0.0/include -I/nix/store/4sswlqrcz5y3s241l0vgrbsyzcrl9gn5-libtermkey-0.20/include -I/nix/store/a0003akn3rdkd7gkzrqk2dn5pk24bhzk-neovim-libvterm-2017-11-05/include -I/nix/store/ivjclr8nncmsn4nf8l9wmljmn79ma81g-jemalloc-5.0.1/include -I/nix/store/p85kjy91dfvs4in358zyfxlksvibw0zn-glibc-2.26-131-dev/include -I/build/source/build/src/nvim/auto -I/build/source/build/include
Compiled by nixbld

Features: +acl +iconv +jemalloc +tui
See ":help feature-compile"

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "
/nix/store/6d9sl52nsaqa8m6mgach4l7fp7dm53q3-neovim-unwrapped-0.2.2/share/nvim"

Run :checkhealth for more info
```

- This plugin version (`git rev-parse --short HEAD`):

```
 ~/projects/nixfromnpm   vs-code-integration  cd ~/.config/nvim/bundle/repos/github.com/autozimu/LanguageClient-neovim && git rev-parse --short HEAD
ad629b1

```

- This plugin's binary version (`bin/languageclient --version`):

```
 ✘  ~/.config/nvim/bundle/repos/github.com/autozimu/LanguageClient-neovim   next  ~/.config/nvim/bundle/repos/github.com/autozimu/LanguageClient-neovim/bin/languageclient --version
languageclient 0.1.105
```

-  Minimal vimrc content:
https://github.com/srghma/dotfiles/blob/0f5ecddb911e04e2ca37bf9734d10f1291407a6c/nvim/init.vim#L246-L255

**Comment by autozimu** [comment] 2018-08-04 19:54
Is it the same issue as in https://github.com/autozimu/LanguageClient-neovim/issues/471?

**Comment by srghma** [comment] 2018-08-04 20:06
@autozimu yes, its the same

**Comment by autozimu** [comment] 2018-08-04 20:43
Duplicate of https://github.com/autozimu/LanguageClient-neovim/issues/471

**Closed by autozimu** 2018-08-04 20:43 UTC
