### ISSUE TITLE
Start a manual diagnostics

### ISSUE THREAD

**Issue by axpira** [autozimu/LanguageClient-neovim#689] opened 2018-12-31 18:22 UTC
## Is your feature request related to a problem? Please describe.
No

## Describe the solution you'd like
A command to start manual diagnostics

## Describe alternatives you've considered
N/A

## Additional context
I set g:LanguageClient_diagnosticsEnable=0 because my computer is very slow and don't want a realtime diagnostics.
Can I start a manual check of diagnostics, only when I want?

**Comment by shuwens** [comment] 2019-02-25 01:44
I believe this should be equivalent to `diagnose on save` or trigger a `full diagnose` via a keymap. I think it is could be an option that some people want. Will this be too complicated to implement?

**Comment by vigilancer** [comment] 2019-03-20 06:43
+1
I also set `g:LanguageClient_diagnosticsEnable=0` because I didn't find a better way how to restrict folders\files diagnostic will run for.
When working with `Dart` code if I go to definition (open files inside of sdk) my 4core OC-ed coffee lake cpu goes mad. After that neovim becomes slow and laggy because of 100% load until I quit it.
Maybe my issue related to dart server implementation but I think this would be quite handy to have the ability to disable diagnostics for sdk sources.

Please enlighten me if there are already knobs for my issue.

**Comment by Anrock** [comment] 2019-03-20 13:51
> Maybe my issue related to dart server implementation but I think this would be quite handy to have the ability to disable diagnostics for sdk sources.

Sounds like this should be tweaked on server side.

**Comment by vigilancer** [comment] 2019-03-20 17:00
@Anrock what do you mean?
Disabling diagnostic is a matter of introducing new flag in client like "dont_send_sources_for_diagnostic_ever" or "dont_ask_for_linter_suggestions".
If you are about sdk sources then server should not care about what sources we throw at it to analyze.
What am I missing here?

**Comment by Anrock** [comment] 2019-03-20 20:28
@vigilancer i'm talking specifically about "no diagnostics for sdk sources" specifically. This is contraversal, but i think that "disable diagnotics for sdk sources"-option generally should be done on server side. 

Otherwise client must know definition and location of sdk sources for every language it's used with. Server, probably being a part of sdk itself, already knows what files belong to sdk and with this option implemented server-side can easily just either drop diagnostic requests or response with empty diagnostics list without actually processing anything.

This can be also implemented as general no-diagnostic black list on client side (of each client), but user would have to populate it manually for each and every language and keep it up to date. Sounds like a lot of duplicated effort for this specific case, given that server, as i said, perfectly knows location of sdk already.
It can be improved by server reporting location of sdk sources to client, but this is not standartized yet (afaik) and would require efforts on both server and each client side, so not much win again.

**Comment by vigilancer** [comment] 2019-03-20 20:49
@Anrock 
Ah, I see. 'SDK sources' was just an example, maybe too specific. This could be vendored libraries in golang or decompiled .java files in java.
My original idea was to allow user of language client to specify blacklist of directories/files that should not be send to server for analysis.

>but user would have to populate it manually for each and every language and keep it up to date

Well, sure user have to populate list with what he wants to exclude from analysis. I personally would not be mind. Thing is it is impossible right now. As for keeping up to date, this is one time thing really.

Thinking about white-/blacklisting maybe this is not so trivial task considering that there are different project structures for different languages. Lists at least need to support globbing.

Less convenient but probably easier to implement would be manual diagnosis. This way one can disable diagnostics completely and send for analysis only specific files\buffers.

**Comment by vigilancer** [comment] 2019-03-20 20:58
>I believe this should be equivalent to diagnose on save or trigger a full diagnose via a keymap. I think it is could be an option that some people want. Will this be too complicated to implement?

My 2 cents on the issue.
Trigger diagnose on save is not very convenient when implemented as is. Because I save files quite often and background diagnosis easily can disturb workflow on slow machines. This solution does not cover cases similar to mine. If we choose to restrict what files are allowed to trigger diagnosis of save we back to black-/whitelisting.

With full diagnose there is another story. How do you define "full"? Is it all opened buffers? Is it all files in current directory? Maybe files that are matching pattern? So we need lists and globbing? You get the idea.

**Comment by Anrock** [comment] 2019-03-20 22:36
@vigilancer 
> Ah, I see. 'SDK sources' was just an example, maybe too specific. This could be vendored libraries in golang or decompiled .java files in java.

Same arguments apply. Server still knows better for which files there is a sense to provide diagnostics.

**Comment by vigilancer** [comment] 2019-03-21 05:39
@Anrock I'm not fully understand you.
It seems odd to me implement some heuristic logic on server side to determine what should or should not be analyzed.
Is your idea that servers should be configurable by user the same way I described earlier?

**Comment by Anrock** [comment] 2019-03-21 05:49
@vigilancer nevermind, this is offtopic anyway.

**Comment by vigilancer** [comment] 2019-03-21 06:31
@Anrock 
Yes, this issue is about "manual check of diagnostics".

But we are discussing now what are the reasons behind this request and alternative ways how we can help it. We talking not about "what this piece of software should do", but "what are best available options to solve problem users of this software encountering".

I suggested black-/whitelists on language client's side, you are saying "this should be server's problem". You are missing the point here. Problem is not "software can't do this", problem is "user can't do that".

Now I'm asking you how user can solve his problem. Where forces could be applied in this structure user-server-client? You suggested to make this a server's problem. I think this is worth discussing.  Is this a really good idea? Because I can see a few cons. 

For example, you have two java projects, and you need to restricted analyzing decompiled sources (idk, maybe by filename pattern), but only in one of them. I can't see how server could be easily configured per project. But for clients this would be trivial with project-specific .vimrc files, for example.

Discussing how this could be solved on server side, even theoretically, at the very least could move us to understanding should or should not it be implemented on client's side. I don't believe this is offtopic and if you have anything to say on the subject please do.

**Comment by Anrock** [comment] 2019-03-21 09:24
@vigilancer ok, if you insist.

Just to avoid any misunderstanding i'm talking about diagnostics for "special" files. Examples: SDK library source code and system libraries, decompiled-on-the-fly bytecode\assembly, dependency packages, generated code and so on.
Generally those files aren't meant to be edited by developer (even if techically possible), only viewed. Therefore there is no sense to waste resources or developer attention on diagnostics for them - developer can't do anything about diagnostics anyway. 
So diagnostics:
a) shouldn't be presented to preserve developer focus 
b) disabled as automatically as possible to avoid interrupting dev focues on fiddling with editor 
c) computer resources shouldn't be spent on producing them to preserve smooth editor interaction

Regarding "what user can do now" - sorry, i can't think of anything better than "nudge the devs, wait until solution is implemented, then wait until better solution is implemented and so on".
I thought about workaround in form of "somehow disable diagnostics for client or server and call lsp functions in client manually", quickly checked config of favourite server and while it's probably possible to do, looks like it would be too crude or cumbersome and rather server-specific, so i didn't post a suggestion about it.

Now about possible solutions:
1) Manually triggered diagnostics. Probably the simplest solution, achieves a) and c), but by design has a flaw of b).

2) Black\white-lists specified in client config. Still has a), factor of b) is decreased - proper white\black listing setup will probably achieve 80-90% effectiveness, however developer would still be required to update lists in case of SDK location change/switch, libraries location change/add and other project-level things. 
There are cases that probably can't be white\black listed: for example haskell lsp server actually compiles temporary files with random names and maintains a mapping between actual source and randomly-named temp files, library file paths are highly dynamic/randomized too. There are also in-memory only buffers, unnamed or with random uuid-like names. To handle them, each client would have to know implementation specifics of each server to provide user a way to address those special files.
Also this solution suffers from c) - despite dropping diagnostics client-side, server still computes them, because server must push diagnostics by spec (if i understand spec correctly).

3) Server-side filtering. Basically this is 2) but with all three criterias achieved. B) is achieved because, as i said earlier, server perfectly knows which files belong to project and which files are "special" so server can populate white\black lists automatically without user intervention and without limitations of filepath-only lists. A) and C) are achieved by server not even producing and pushing diagnostics for "special" files in the first place. Server would still have to provide user a way to address this files, but it will be contained in server config file therefore remain server-specifc and client-agnostic

Solution 3) also covers case you described:
> For example, you have two java projects, and you need to restricted analyzing decompiled sources (idk, maybe by filename pattern), but only in one of them. I can't see how server could be easily configured per project.

As i said, server automatically populates black/white lists and as sane default (imo), server will blacklist decompiled source. But that doesn't mean the lists are frozen and mechanism for per-project configuration [already exists](https://github.com/autozimu/LanguageClient-neovim/blob/15cc7c72eea9e7128daa17298e2dc0eec07fef27/doc/LanguageClient.txt#L204). By means of this settings file it would be possible to tell the server to produce diagnostics for decompiled files on per-project basis.

If i've failed to answer you question(s), i'm sorry. It would be helpful if you formulate them in form of bulleted list so i can address them more specifically.

**Comment by vigilancer** [comment] 2019-03-21 14:03
@Anrock thank you for extended answer.

Initially I was under impression that you are suggesting move guessing game "should this file be diagnosed" to server completely. So you basically talking about sane defaults on server side with server accepting additional diasnostic [configurations](https://microsoft.github.io/language-server-protocol/specification#workspace_configuration).

I took a quick look on [LSP](https://microsoft.github.io/language-server-protocol/img/language-server-sequence.png) [specs](https://microsoft.github.io/language-server-protocol/specification). Seems protocol is the only limiting factor to implement both 2) and 3) solution.

I agree that sane defaults on server side would be nice thing to have. Sanity of defaults is somewhat that seems to me like implementation dependant thing and may vary. Let’s asume least sane defaults - server does not provide any intellectual filtering on it’s own. Still server had to know how to work with black/white lists.

I found nothing in the last version on protocol (v3.14.0 12/13/2018) that can be used for our purpose directly. The only hacky way I can think of is to toggle `g:LanguageClient_diagnosticsEnable`, restart server and re-[init](https://microsoft.github.io/language-server-protocol/specification#initialize) connection.

As for 1) this sounds easy but in practice I found nothing in protocol specs to trigger re-run of diagnostics, maybe false `textDocument/didChange` event will do but this still smells.

Some random thoughts.
During [initial handshake](https://microsoft.github.io/language-server-protocol/specification#initialize) client sends to server `TextDocumentClientCapabilities`:
```
/**
 * Text document specific client capabilities.
 */
export interface TextDocumentClientCapabilities {
 ///…. skipped ///
	/**
	 * Capabilities specific to `textDocument/publishDiagnostics`.
	 */
	publishDiagnostics?: {
		/**
		 * Whether the clients accepts diagnostics with related information.
		 */
		relatedInformation?: boolean;
	};
```

IIRC from sources `g:LanguageClient_diagnosticsEnable` option does not trigger `relatedInformation` flag during initialization, it is used locally to filter out incomming [`PublishDiagnostics Notification`](https://microsoft.github.io/language-server-protocol/specification#textDocument_publishDiagnostics).
Maybe it is possible to hook up there.

Workaround I would suggest by now is to set `g:LanguageClient_diagnosticsEnable = 0` and use external static analyzer.

For example, Dart SDK have [dartanalyzer](https://github.com/dart-lang/sdk/tree/master/pkg/analyzer_cli#dartanalyzer) and [dart-lang/dart-vim-plugin](https://github.com/dart-lang/dart-vim-plugin) provide command `:DartAnalyzer`.

**Comment by martskins** [comment] 2020-07-14 07:49
Afaik we don't have control over when the server computes the diagnostics, so I don't think you can limit this to a specific set of events vim-side. So I second @vigilancer 's opinion on this and I'll add `dense-analysis/ale` to the list of suggestions for this. That should give you more control over when you run lints/fixes, but it won't necessarily use the same sources for those diagnostics.

Considering that, I'll close this one as I don't think there's much we can do about this, but feel free to re-open if you still have any doubts.

**Closed as completed by martskins** 2020-07-14 07:49 UTC
