### ISSUE TITLE
Feature request - server start command and specify socket address

### ISSUE THREAD

**Issue by mnussbaum** [autozimu/LanguageClient-neovim#449] opened 2018-05-25 23:23 UTC
First off just want to say thanks for the awesome language client! 

I'm hoping to use this project with the Ruby language server [solargraph](https://github.com/castwide/solargraph/), which I believe doesn't handle input via STDIN. I'd really like to be able to define both a start command for the solargraph server, as well as the socket address to reach it at. This would let me take advatange of your existing work to manage the server child process even with non-cooperative language servers.

**Comment by dkarter** [comment] 2018-05-30 16:14
Yes! I really want this too.

**Comment by megalithic** [comment] 2018-06-12 01:21
will chime in here and say i just discovered solargraph, and would love to use it with LC-neovim, too! thanks @autozimu!

**Comment by vtm9** [comment] 2018-06-19 17:25
https://blog.schembri.me/post/solargraph-in-vim/
It works for me

**Comment by goronfreeman** [comment] 2018-06-20 02:55
I was able to get it work from the article @vtm9 posted, but it requires running `solargraph socket` manually outside of vim. It would be nice to be able to have the server start automatically in the background. Is there some way to do this that I'm not seeing?

**Comment by vtm9** [comment] 2018-06-20 05:43
Currently no. Maybe later, if solargraph maintaner will make stdin interface.

**Comment by autozimu** [comment] 2018-06-20 16:08
https://github.com/castwide/solargraph/issues/65

**Comment by milch** [comment] 2018-07-18 21:25
Solargraph added the STDIO interface, and I can confirm that it works with this project 👍

**Comment by autozimu** [comment] 2018-07-19 01:43
Since solargraph has added stdio interface, there is no immediate benefits adding this support. Closing for now.

**Closed as completed by autozimu** 2018-07-19 01:43 UTC
Labels: feature request
