### ISSUE TITLE
Serious perfromance degradation in one of the latest releases

### ISSUE THREAD

**Issue by whitebyte** [autozimu/LanguageClient-neovim#660] opened 2018-11-20 09:17 UTC
After one of latest updates LanguageClient suddenly became slow and unresponsive. I throws tons of `timed out waiting on channel` and it takes up to 10-20 seconds to perform any action (rename, goto def). I update LanguageClient almost every day, so unfortunalely can't say when exactly it started. 

I'm working on the same projects as before, nothing too fancy. I use language servers for node, PHP and ruby. This behaviour persists regardless of languages and projects, so I think it's related to LanguageClient.

I understand that it sounds pretty vague, will be happy to provide more details.

**Comment by autozimu** [comment] 2018-11-20 17:35
Could you try with a fresh install and on a simpler project?

I couldn't reproduce the issue you described.

Another thing to note is that if the project is large, language server might take some time to index. If you issue a command before the server is ready, the command might results a timeout, and subsequent commands might be affected (I know this should be fixed, but I haven't found a reliable way to reproduce and enough time to fix).

**Comment by teasp00n** [comment] 2018-11-21 09:48
I have the same problem. Have tracked it down to this commit: https://github.com/autozimu/LanguageClient-neovim/commit/2a79bb680cecd2a0f44bf750b9a3fddc5694fa8a

I'll do something like `LanguageClient_textDocument_documentSymbol()` and it will perform as expected for the first call. Subsequent calls will produce the timed out waiting on channel error.

**Comment by autozimu** [comment] 2018-11-21 17:47
@teasp00n Thanks a lot for the data point. I am able to reproduce the issue.

**Closed as completed** 2018-11-21 18:27 UTC
