### ISSUE TITLE
FZF preview not respecting line numbers

### ISSUE THREAD

**Issue by harshasrisri** [autozimu/LanguageClient-neovim#1095] opened 2020-09-15 22:50 UTC
- Did you upgrade to latest plugin version?
Yes

- Did you upgrade to/compile latest binary? Run shell command `bin/languageclient --version` to get its version number.
- (Neovim users only) Did you check output of `:checkhealth LanguageClient`?
```
health#LanguageClient#check
========================================================================
  - OK: binary found: /Users/harshasrisri/.rc/dot/vim/plugins/LanguageClient-neovim/bin/languageclient
  - OK: languageclient 0.1.158 0e5c9546bfddbaa2b01e5056389c25aefc8bf989
  - OK: Floating window is supported and will be used for hover
```

- Did you check [troubleshooting]?
Yes

[troubleshooting]: https://github.com/autozimu/LanguageClient-neovim/blob/next/INSTALL.md#troubleshooting

## Describe the bug
FZF in SelectionUI doesn't scroll preview window based on the line numbers in results, where as native FZF commands (like `:Rg`) do scroll the preview window appropriately.

## Environment
- neovim version 0.4.3
- Minimal vimrc content (A minimal vimrc is the smallest vimrc that could reproduce the issue.
```
    function! LCN_Mappings()
        let g:LanguageClient_fzfOptions = fzf#vim#with_preview().options
        let g:LanguageClient_fzfContextMenu = 1
        let g:LanguageClient_serverCommands = {
                    \ 'rust' : ['rustup', 'run', 'stable', 'rls'],
                    \ 'cpp'  : ['ccls', '--log-file=/tmp/ccls.log'],
                    \ 'c'    : ['ccls', '--log-file=/tmp/ccls.log'],
                    \ }

        set omnifunc=LanguageClient#complete
        set completefunc=LanguageClient#complete
        set formatexpr=LanguageClient#textDocument_rangeFormatting()
        set signcolumn=yes

        " Mappings go here...
    endfunction

    function! LCN_Highlighting(running) abort
        if a:running.result
            call LanguageClient#textDocument_documentHighlight()
        endif
    endfunction

    augroup LCN_AutoCommands
        au!
        au FileType rust,c,cpp silent call LCN_Mappings()
        au CursorMoved,CursorMovedI *.rs,*.c,*.cpp,*.h,*.cc,*.hh silent call LanguageClient#isAlive(function('LCN_Highlighting'))
    augroup END

```
- Language server link and version: `ccls` (latest)

## To Reproduce
Configure fzf options to use preview window. 
- Execute any native fzf actions (like `:Rg`) and see that the preview window scrolls according to line number in result
- Execute any LanguageClient functions and see that the preview window always shows the beginning of the file

## Current behavior
Execute any LanguageClient functions and see that the preview window always shows the beginning of the file

## Expected behavior
Execute any LanguageClient functions the file in preview window should be scrolled according to line number in result

## Screenshots
- Execute `:Rg`
<img width="952" alt="Screen Shot 2020-09-15 at 3 40 43 PM" src="https://user-images.githubusercontent.com/750691/93272527-89e06500-f76a-11ea-8b19-24ec3f91ec74.png">

- Execute `:call LanguageClient#textDocument_references()`
<img width="952" alt="Screen Shot 2020-09-15 at 3 39 00 PM" src="https://user-images.githubusercontent.com/750691/93272561-995fae00-f76a-11ea-9635-d6819ecbdc2a.png">

## Additional Comments
I remember this feature was working as expected. Don't know which update caused it to not work as expected anymore.
```
:echo fzf#vim#with_preview().options
['--preview', '''/Users/harshasrisri/.rc/dot/vim/plugins/fzf.vim/bin/preview.sh'' {}']
```

**Comment by martskins** [comment] 2020-09-16 07:57
I'm getting the preview in the correct lines (ignoring the fact that I don't have line numbers or highlighting for it) and scrolled to the correct position as well. I tested this after updating all plugins and updating my config to match the on you shared here.

![image](https://user-images.githubusercontent.com/4250565/93308366-125a1680-f7fa-11ea-8c79-fc86bcdc6f94.png)

**Comment by harshasrisri** [comment] 2020-09-16 18:31
@martskins Thank you for testing this. Could you suggest ways to debug this on my end? If you could share your FZF config, if any, that would be great, too.

**Comment by Kypert** [comment] 2020-09-28 07:20
I think that I see the same issue, I am using this combination:
languageclient 0.1.158 0e5c9546bfddbaa2b01e5056389c25aefc8bf989
fzf.vim 3348aef05d02828cd8b071ab29476af2029ea3d3

It looks like the script `fzf.vim/bin/preview.sh` was changed to support scrolling (Ctrl-arrows), by removing the --line-range and instead use native fzf to find the location. For me, it helped by adding this patch:

```
diff --git a/autoload/LanguageClient.vim b/autoload/LanguageClient.vim
index 7b566e5..d03c7bf 100644
--- a/autoload/LanguageClient.vim
+++ b/autoload/LanguageClient.vim
@@ -231,6 +231,7 @@ function! s:FZF(source, sink) abort
     if l:options is v:null
         if exists('*fzf#vim#with_preview')
             let l:options = fzf#vim#with_preview('right:50%:hidden', '?').options
+            let l:options = ['--delimiter', ':', '--preview-window', '+{2}-5'] + l:options
         else
             let l:options = []
         endif
```

Which is what fzf.vim is using for Rg/Grep/etc. It is not clear to me where the location-parsing is done, but it seems to work :)

**Comment by martskins** [comment] 2020-10-17 10:07
I changed my computer a few days ago and I managed to reproduce it now. The patch @Kypert suggested works for me too, but I had to add it when options was not `v:null` as well. 
I feel like adding that patch into LCN is a little weird though, because it could potentially mess up with the user provided options, so I feel like the best thing to do is to just add it in your config (we could probably add this to the docs somewhere).

So just to be clear, using this fixed the issue for me:

`let g:LanguageClient_fzfOptions = ['--delimiter', ':', '--preview-window', '+{2}-5'] + fzf#vim#with_preview().options`

I will close this issue now as a solution has been provided, but feel free to re-open if you feel like discussing it more.

**Closed as completed by martskins** 2020-10-17 10:07 UTC
