### ISSUE TITLE
Deoplete autocompletes without confirming selection

### ISSUE THREAD

**Issue by chrisduerr** [autozimu/LanguageClient-neovim#1052] opened 2020-06-14 00:55 UTC
It seems like the LanguageClient-neovim plugin does not interact nicely with
deoplete. Occasionally completions are confirmed during typing without
confirmation from the user.

This has been reported to deoplete in
https://github.com/Shougo/deoplete.nvim/issues/1013.

It seems like LanguageClient-neovim uses the deprecated is_async API
(https://github.com/autozimu/LanguageClient-neovim/blob/next/rplugin/python3/deoplete/sources/LanguageClientSource.py#L29),
which seems to cause troubles in combination with deoplete completions.

There is a reference on how Shougo implemented neovim's built-in language client
[here](https://github.com/Shougo/deoplete-lsp), however it might be a bit
confusing since it's a lot of different languages interacting with each other.

According to Shougo the recommended API for completion is
`deoplete#auto_complete()`.

**Comment by benjamingorman** [comment] 2020-06-14 20:18
I'm experiencing this as well and it's quite annoying. Is there any workaround for the moment?

**Comment by martskins** [comment] 2020-06-14 23:00
I'm not sure if I understood the problem correctly, but I think I couldn't reproduce it, as I don't see any unexpected behaviour with completion. Could you provide a minimal vimrc to try and reproduce this issue?

**Comment by chrisduerr** [comment] 2020-06-15 01:23
It might depend on which language client is used? I've used `rust-analyzer` myself I'm pretty sure with RLS this didn't happen (or at least not as often?), but that had pretty poor results anyways.

So minimal config would just be languageclient-neovim, rust-analyzer and deoplete.

Since this seems to be a an async problem that pops up when using the deprecated API, it probably takes a while to reproduce though. I've personally found no reliable way to reproduce, it just pops up every once in a while.

**Comment by benjamingorman** [comment] 2020-06-16 11:04
I've tried to get a minimal .vimrc to reproduce this but can't find a way to do it consistently. I'll keep trying but I have noticed a consistency which is that the problem onyl happens when there is only one result suggested by LanguageClient/server. Then sometimes it will automatically complete that result without confirmation. Also I know this isn't much to go off for debugging but the faster you type the more often the problem seems to occur! If I type slowly it almost never happens.

This isn't consistent but to give an example: using the latest LanguageClient with a javascript file and `javascript-typescript-stdio` language server
```
x = {
  examplepropertyname: 42
}
```
Paste this into a new buffer and start typing `x.example`, occasionally the whole property name will be autocompleted without confirmation and you will end up with `examplepropertynamepropert` (since your hands naturally continue typing until your brain realises the autocomplete happened).

**Comment by benjamingorman** [comment] 2020-06-16 11:07
A comment on the deoplete issue says that using `set completeopt=menu,noselect` fixes the issue. It's possible that the bug may be entirely in deoplete and not caused by LanguageClient at all. I'll try that workaround and see if it helps.

**Comment by Shougo** [comment] 2020-06-16 11:17
@benjamingorman Have you set complete opt in vimrc?
`:verbose set completeopt?`

And it is better.

```vim
set completeopt+=noselect
```

or remove `noinsert` from your `completeopt`.

**Comment by Shougo** [comment] 2020-06-16 11:26
@benjamingorman Please test this PR.
https://github.com/Shougo/deoplete.nvim/pull/1104

**Comment by chrisduerr** [comment] 2020-06-16 15:36
Based on some short 5-10 min testing, I was able to reproduce the issue multiple times with deoplete master but wasn't able to reproduce it with your PR @Shougo. I have my `completeopt` set to just `menu`.

I wouldn't take this as a guarantee, but it seems to at least make things better maybe? I'll report back if there are any problems popping up.

Though I'm curious what this would mean for LanguageClient-neovim. Is it doing everything right then, or is this just a patch to work around an issue with a deprecated API that should still be replaced?

**Comment by chrisduerr** [comment] 2020-06-16 16:47
I'm pretty sure I was just able to reproduce it even with that branch. It might still improve things, but I don't think it fixes it completely.

**Comment by Shougo** [comment] 2020-06-17 00:05
@chrisduerr I have improved the branch.  Please update it.

> or is this just a patch to work around an issue with a deprecated API that should still be replaced?

The fix is workaround for the deprecated feature.

**Comment by chrisduerr** [comment] 2020-06-17 01:04
Thanks, I've updated to the latest version and will report back tomorrow if everything works out. So far it works, but that doesn't really mean much.

**Comment by Shougo** [comment] 2020-06-18 11:28
@chrisduerr Ping.

**Comment by chrisduerr** [comment] 2020-06-18 20:39
Sorry, I kinda got lost in some other things. Everything has been working without problems so far!

**Comment by Shougo** [comment] 2020-06-18 23:32
OK.  I will merge it.  Thanks.

**Comment by Shougo** [comment] 2020-06-18 23:37
I have merged.

**Comment by martskins** [comment] 2020-07-01 20:03
@chrisduerr assuming you didn't have any other issues with this I'm gonna close this, but feel free to re-open if it happens again.

**Closed as completed by martskins** 2020-07-01 20:03 UTC

**Comment by chrisduerr** [comment] 2020-07-01 20:34
I feel like it might still be worth to move off of the deprecated API?
