### ISSUE TITLE
SignatureHelp not working with ccls

### ISSUE THREAD

**Issue by MarkGreeny** [autozimu/LanguageClient-neovim#693] opened 2019-01-07 00:42 UTC
Hi, 

according to this [issue](https://github.com/MaskRay/ccls/issues/192) on ccls, `textDocument/signatureHelp' should be working on their side. Yet when I call it from the client, there are no results.

Can you please help me to get `textDocument/signatureHelp` working with ccls? As it is, it does not work when calling `LanguageClient#textDocument_signatureHelp()`. How should I go about making it work?

Note that i have the latest version of both this client and ccls.

**Comment by autozimu** [comment] 2019-01-15 02:56
Can you follow the issue template?

**Comment by dimbleby** [comment] 2019-01-15 13:48
probably fixed by #688 I think - looks like ccls uses the label offset style for which supported was added by that merge request.

**Comment by autozimu** [comment] 2019-01-20 23:25
@MarkGreeny Can you verify?

**Comment by przemkovv** [comment] 2019-04-11 00:52
I can confirm that `LanguageClient#textDocument_signatureHelp()` works with `ccls` very well now.

**Comment by martskins** [comment] 2020-11-08 11:09
Closing as stale and as it seems to be working now

**Closed as completed by martskins** 2020-11-08 11:09 UTC
