### ISSUE TITLE
got a segfault

### ISSUE THREAD

**Issue by vito-c** [autozimu/LanguageClient-neovim#643] opened 2018-10-29 19:13 UTC
- Did you upgrade to latest plugin version? 
yes
- Did you upgrade to/compile latest binary? Run shell command
  `bin/languageclient --version` to get its version number. 
yes
- (Neovim users only) Did you check output of `:checkhealth LanguageClient`?
yes
- Did you check [troubleshooting]?
yes

[troubleshooting]: https://github.com/autozimu/LanguageClient-neovim/blob/next/INSTALL.md#6-troubleshooting

## Describe the bug
I got a segfault when opening a bash file.

Language server sc...Segmentation fault: 11Unable to read from language server

## Environment
- neovim/vim version (`nvim --version` or `vim --version`): v0.3.1
- This plugin version (`git rev-parse --short HEAD`):  `283dba5`
- This plugin's binary version (`bin/languageclient --version`): `languageclient 0.1.123 283dba5754055c74e250166a99017914624625b1`
- Minimal vimrc content (A minimal vimrc is the smallest vimrc that could
  reproduce the issue. Refer to an example [here][min-vimrc.vim]):
- Language server link and version:

[min-vimrc.vim]: https://github.com/autozimu/LanguageClient-neovim/blob/next/min-vimrc.vim

## To Reproduce
1. I was editing a scala file then switched to a bash file and got a segfault.
2. I'm not sure where the log is stored or i'd post it

**Comment by autozimu** [comment] 2018-11-12 22:40
If you're indeed using referenced vimrc, then the log files can be found at https://github.com/autozimu/LanguageClient-neovim/blob/next/min-vimrc.vim#L23-L24

Where is this segment happens? Did it happen to the language server or this client or vim/neovim itself?

**Comment by RobbieClarken** [comment] 2018-12-17 08:21
Thanks for this excellent vim plugin!

I can reliably trigger a segfault by:
1. Configuring LaunguageClient-neovim to use [python-language-server](https://github.com/palantir/python-language-server)
2. Opening a python file in vim (the file can be empty)
3. At the exact moment vim starts, hitting `/x` (where `x` can be any character)

The last step needs to be within milliseconds of launching vim, so it doesn't happen that often in normal use.

The error is:

```
Vim: Caught deadly signal SEGV

Vim: Finished.
Segmentation fault: 11
```

Here is my vimrc:

```
set nocompatible

call plug#begin('~/.vim/plugged')
Plug 'autozimu/LanguageClient-neovim', {
  \ 'branch': 'next',
  \ 'do': 'bash install.sh',
  \ }
call plug#end()

let g:LanguageClient_serverCommands = {
  \ 'python': ['/usr/local/bin/pyls'],
  \ }
```

The log files don't show much:

<details>
<summary>LanguageClient.log</summary>

```
#######
LanguageClient 0.1.132 cffa8b55eb93d33bc00795c8c85ea7dc6912f21f
#######
18:57:49 WARN main src/utils.rs:72 Unknown project type. Fallback to use dir as project root: Ok("/Users/clarkr")
18:57:49 WARN main src/languageclient.rs:900 Failed to get initializationOptions: Failed to read file (/Users/clarkr/.vim/settings.json): No such file or directory (os error 2)
```
</details>

LanguageServer.log is empty.

If I let vim start normally without triggering the segfault I get:

<details>
<summary>LanguageClient.log</summary>

```
#######
LanguageClient 0.1.132 cffa8b55eb93d33bc00795c8c85ea7dc6912f21f
#######
18:58:14 WARN main src/utils.rs:72 Unknown project type. Fallback to use dir as project root: Ok("/Users/clarkr")
18:58:14 WARN main src/languageclient.rs:900 Failed to get initializationOptions: Failed to read file (/Users/clarkr/.vim/settings.json): No such file or directory (os error 2)
18:58:14 WARN main src/languageclient.rs:2780 Failed to get workspace settings: Failed to read file (/Users/clarkr/.vim/settings.json): No such file or directory (os error 2)
18:58:14 WARN main src/languageclient.rs:2105 Failed to start language server automatically. Language client has already started for language python.
```
</details>

<details>
<summary>LanguageServer.log</summary>

```
2018-12-17 18:58:14,678 UTC - WARNING - pyls.config.config - Failed to load pyls entry point 'autopep8': No module named 'autopep8'
2018-12-17 18:58:14,683 UTC - WARNING - pyls.config.config - Failed to load pyls entry point 'mccabe': No module named 'mccabe'
2018-12-17 18:58:14,684 UTC - WARNING - pyls.config.config - Failed to load pyls entry point 'pycodestyle': No module named 'pycodestyle'
2018-12-17 18:58:14,684 UTC - WARNING - pyls.config.config - Failed to load pyls entry point 'pydocstyle': No module named 'pydocstyle'
2018-12-17 18:58:14,685 UTC - WARNING - pyls.config.config - Failed to load pyls entry point 'pyflakes': No module named 'pyflakes'
2018-12-17 18:58:14,686 UTC - WARNING - pyls.config.config - Failed to load pyls entry point 'rope_completion': No module named 'rope'
2018-12-17 18:58:14,687 UTC - WARNING - pyls.config.config - Failed to load pyls entry point 'rope_rename': No module named 'rope'
2018-12-17 18:58:14,688 UTC - WARNING - pyls.config.config - Failed to load pyls entry point 'yapf': No module named 'yapf'
```
</details>


Environment:

* macOS 10.13.3
* vim 8.1
* LanguageClient-neovim commit 12a1f60
* python-language-server 0.21.4

Hope this helps you debug. Let me know if you want me to try any experiments.

**Comment by jkrup** [comment] 2019-01-07 22:37
I am also getting this error reproducible by doing either `/[ANYKEY]` or `:[ANYKEY]` right when opening a JS file.

* MacOS 10.13.6
* vim 8.1
* javascript-typescript-stdio

**Comment by autozimu** [comment] 2019-01-08 05:52
@RobbieClarken Thanks for the detailed reproduction steps.

I will check back when got some time.

**Comment by lambdahands** [comment] 2019-01-30 18:13
I'm also having this issue when I open a JS file and immediately type `/` or `:` followed by a key.

- MacOS 10.13.6
- nvim v0.3.1
- flow-language-server

**Comment by mngyuan** [comment] 2020-07-21 22:22
I was also having this exact issue opening a js file with nvim v0.3.1, but I updated to nvim v0.4.3 through brew and it's working fine now

**Comment by martskins** [comment] 2020-10-17 15:03
Can't reproduce this myself. I'll close it as it seems to be solved by upgrading nvim but feel free to re-open if it's still happening to you.

**Closed as completed by martskins** 2020-10-17 15:03 UTC
Labels: insufficient repro steps/info
