### ISSUE TITLE
[question] Is there any way to set the quickfix severity

### ISSUE THREAD

**Issue by donotnoot** [autozimu/LanguageClient-neovim#991] opened 2020-03-16 18:36 UTC
As the title says, I can't seem to find any way to filter what goes to the quickfix list by severity.

It's nice to see the hints, infos and warnings on the buffer but when jumping around I'm generally only interested to go to errors. Is there any way I can make the quickfix show errors only?

**Comment by jounathaen** [comment] 2020-03-26 14:42
Probably a duplicate of https://github.com/autozimu/LanguageClient-neovim/issues/726
The solution is to set `g:LanguageClient_diagnosticsMaxSeverity`. See https://github.com/autozimu/LanguageClient-neovim/blob/8a2396d614579f4b17b33ec942037936b3a73625/doc/LanguageClient.txt#L388

**Comment by donotnoot** [comment] 2020-03-28 13:16
@jounathaen I tried that, but that removes stuff globally, I would like to filter stuff from the quickfix only, so that for example quickfix contains only warning and errors but the virtual diagnostic text contains also infos and notices. I don't think there is anything to do that, right? I guess I could write a plugin that filters the quickfix stuff, but just wanted to make sure this is not a feature that exists yet.

**Comment by martskins** [comment] 2020-10-17 11:57
I'll close this one as I don't think there are plans to work on this, it sounds a little too specific. PRs are always welcome though, so happy to help if you want to give this a go.

**Closed as completed by martskins** 2020-10-17 11:57 UTC
