### ISSUE TITLE
textDocument_formatting_sync() does not add missing imports for gopls

### ISSUE THREAD

**Issue by klnusbaum** [autozimu/LanguageClient-neovim#854] opened 2019-07-19 03:09 UTC
- Did you upgrade to latest plugin version?
yes
- Did you upgrade to/compile latest binary? Run shell command
  `bin/languageclient --version` to get its version number.
yes
languageclient 0.1.146 ec4af74cc389f802c3c43a660c963049848a8a93

- (Neovim users only) Did you check output of `:checkhealth LanguageClient`?
Yes. It's all good
- Did you check [troubleshooting]?
yes.

[troubleshooting]: https://github.com/autozimu/LanguageClient-neovim/blob/next/INSTALL.md#6-troubleshooting

## Describe the bug
When running textDocument_formatting_sync(), missing imports are not added to go files

## Environment
- neovim/vim version (`nvim --version` or `vim --version`): v0.3.8
- This plugin version (`git rev-parse --short HEAD`): 5491a64
- This plugin's binary version (`bin/languageclient --version`): 0.1.146 ec4af74cc389f802c3c43a660c963049848a8a93
- Minimal vimrc content:
```
call plug#begin('~/.local/share/nvim/plugged')
Plug 'autozimu/LanguageClient-neovim', {
  \ 'branch': 'next',
  \ 'do': 'bash install.sh',
  \ } 
call plug#end()
let g:LanguageClient_serverCommands = {
  \ 'go': ['gopls'] }
autocmd BufWritePre *.go :call LanguageClient#textDocument_formatting_sync()
```
- Language server link and version:
[gopls][gopls-github] v0.0.1-20190607+alpha, built in $GOPATH mode

[gopls-github]: https://github.com/golang/go/wiki/gopls
## To Reproduce
1. mkdir -p $GOPATH/src/com.test.test/playground
2. cd $GOPATH/src/com.test.test/playground
3. nvim main.go
4. Write the following to your file:
```
package playground

func main() {
	fmt.Println("doing stuff")
}
```

## Current behavior
Upon writing the file, the `fmt` package is not imported.

## Expected behavior
Upon writing the file, the `fmt` package should be imported.

**Comment by Genki-S** [comment] 2019-07-19 04:42
I'm just investigating this. I haven't found the solution but let me share my findings so far just in case it helps someone.

First of all, I think the current behavior is not a bug in LanguageClient-neovim side. Even though [gopls wiki](https://github.com/golang/go/wiki/gopls) claims running `:call LanguageClient#textDocument_formatting_sync()` should run `goimports`, I'm not seeing any code in `gopls` which is invoking `goimports` feature (see code [here](https://github.com/golang/tools/blob/c6e1543aba625eb8e00a24270b07e67eb90c4108/internal/lsp/source/format.go#L21-L44)). Also considering the fact `:call LanguageClient#textDocument_formatting_sync()` do have an effect of `gofmt` (not `goimports`), it seems to me that LanguageClient-neovim is succeeding to calling and applying `textDocument/formatting` method. It's just gopls not running `goimports` upon `textDocument/formatting` method. (i.e. the gopls wiki should be fixed)

gopls provides `source.organizeImports` code action, which should apply `goimports` feature, so I'm trying to use this instead. This is the log from LanguageClient-neovim when I'm running `:call LanguageClient#textDocument_codeAction()`:

```
13:12:19 INFO writer-Some("go") src/rpcclient.rs:215 => Some("go") {"jsonrpc":"2.0","method":"textDocument/codeAction","params":{"context":{"diagnostics":[]},"range":{"end":{"character":0,"line":0},"start":{"character":0,"line":0}},"textDocument":{"uri":"file:///home/genki/tmp/main.go"}},"id":4}
13:12:19 INFO reader-Some("go") src/rpcclient.rs:169 <= Some("go") {"jsonrpc":"2.0","result":[{"title":"Organize Imports","kind":"source.organizeImports","edit":{"changes":{"file:///home/genki/tmp/main.go":[{"range":{"start":{"line":3,"character":0},"end":{"line":3,"character":0}},"newText":"\t\"fmt\"\n"}]}}}],"id":4}
13:12:19 ERROR unnamed src/rpchandler.rs:13 Error handling message: missing field `command`
```
(notice that the response from gopls seems to be having the right "edit" field, which is adding `fmt` package to the file)

It seems LanguageClient-neovim expects `command` field to be present. However, gopls seems to think the `command` field to be optional (and doesn't provide the field with `source.organizeImports` code action):
```
	/*Command defined:
	 * A command this code action executes. If a code action
	 * provides a edit and a command, first the edit is
	 * executed and then the command.
	 */
	Command *Command `json:"command,omitempty"`
```
(original code [here](https://github.com/golang/tools/blob/c6e1543aba625eb8e00a24270b07e67eb90c4108/internal/lsp/protocol/tsprotocol.go#L3179-L3210))

I don't know which is correct, so I'm planning to read LSP spec next.

**Comment by klnusbaum** [comment] 2019-07-19 04:49
I think you're right. This seems to be an issue with gopls more than LanguageClient-neovim. Or maybe, stated differently, gopls implements `textDocument_formatting_sync()` in a way that's different from, say, Rust. If you run `gopls format <file>` you'll see it also doesn't add missing imports. I seem to remember there being some discussion on the gopls project about having the format command add missing imports, but I can't seem to find that right now.

**Comment by klnusbaum** [comment] 2019-07-19 04:53
Ah, ok, they just haven't added the organize imports functionality to the command line yet, but apparently it does exists:
https://github.com/golang/go/issues/31979

**Comment by Genki-S** [comment] 2019-07-19 08:10
As for using `source.organizeImport` code action, I found the problem is already solved in #805.
I confirmed by using `bin/languageclient` built on the latest `next` branch (5491a64a07b259568e26981e5ec0d78ba8cec756), I can run `source.organizeImport` code action by running `:call LanguageClient#textDocument_codeAction()`.
Probably it's a good idea to create a new release?

If someone want to build `bin/languageclient`, apply the following patch and run `./install.sh`:
```
diff --git i/install.sh w/install.sh
index 5aab36e..0e61411 100755
--- i/install.sh
+++ w/install.sh
@@ -20,14 +20,7 @@ try_wget() {
 }

 download() {
-    echo "Downloading bin/${name}..."
-    url=https://github.com/autozimu/LanguageClient-neovim/releases/download/$version/${1}
-    if (try_curl "$url" || try_wget "$url"); then
-        chmod a+x bin/$name
-        return
-    else
-        try_build || echo "Prebuilt binary might not be ready yet. Please check minutes later."
-    fi
+    try_build || echo "Prebuilt binary might not be ready yet. Please check minutes later."
 }

 try_build() {
```

So I'm guessing there's nothing to do on LanguageClient-neovim side. <s>I'm closing this issue.</s> (I don't see close button...)

**Comment by autozimu** [comment] 2019-07-19 16:55
Sorry for the late and thanks for the investigation.

I will publish a new release shortly.

**Closed as completed by autozimu** 2019-07-19 16:55 UTC

**Comment by autozimu** [comment] 2019-07-19 16:57
New release has been cut and binaries shall be available within hours.

**Comment by klnusbaum** [comment] 2019-07-19 22:33
sorry, still a little unclear here. What's the exact solve? How do I run `source.organizeImport` with `call LanguageClient#textDocument_codeAction()`?

**Comment by Genki-S** [comment] 2019-07-20 05:07
Thanks for releasing! (that was lightning fast btw, thanks much!)

@klnusbaum Here's the summary:
- Upgrade to latest `bin/languageclient` binary (re-running `install.sh` should do I guess)
- Open the go file in the issue description (the one we want "fmt" package to be automatically added)
- Type `:` to enter command mode
- Type `call LanguageClient#textDocument_codeAction()`, hit Enter
- LanguageClient-neovim should show a list of Code Actions available, most likely it will contain "Organize Imports" item only
- Hit Enter to select "Organize Imports" action
- In the go file, "fmt" package should be added as expected

Hope this helps.

**Comment by klnusbaum** [comment] 2019-07-20 16:00
@Genki-S ah, thank you. That makes sense. In that case, I have a couple follow up questions:

1. I ran `PlugUpdate` to get the new version of the LSP client. It updated and it looks like I've got the latest version now (`languageclient 0.1.147 e4478a4789805c66ce24ae786677ae557cd411da`). However, when I run `call LanguageClient#textDocument_codeAction()` I get the following error:

`[LC] FZF not loaded!`

My understanding was FZF was optional for this vim plugin and I'm not sure why it would be needed for this particular operation. Is there a way to get this to work without FZF?

2. If I want the imports to be organized on every save, what would I put in my .vimrc file? I tried something like:

```
call LanguageClient#textDocument_codeAction() "source.organizeImports"
```

But that also got the FZF error

**Comment by klnusbaum** [comment] 2019-07-20 16:02
Oh, wait, I see, it says in the README I need FZF for multi-entry UI selection. So that clears up point 1 for me.

I guess the question for item 2 still stands though. Is there a way to organizeImports on every write of a go file?

**Comment by Genki-S** [comment] 2019-07-21 04:52
I'm afraid I haven't found an existing solution to do this automatically on save.

Here's what I'd do if I want to implement organize-on-save:
- Implement an variant of `LanguageClient#textDocument_codeAction()` which takes Code Action name and execute it instead of letting user select action (probably I'd call it `LanguageClient#textDocument_codeAction_select(actionName)`)
  - this seems similar to what coc.nvim is [doing](https://github.com/neoclide/coc.nvim/blob/6c3442061510904d3b2bc02a60d8905bbc79571e/src/handler/index.ts#L239-L251)
- Call the new method upon `BufWritePre`
  - `autocmd BufWritePre *.go :call LanguageClient#textDocument_codeAction_select("source.organizeImports")`

I might try sending pull request if this gets traction, but actually I found myself preferring to invoke `source.organizeImports` intentionally so I'm not confident if I'll do this. (If you think about it, adding an import statement is a significant change to your file, it introduces new dependency. I'd rather do that operation consciously)

**Comment by klnusbaum** [comment] 2019-07-23 14:34
Yea, I guess I don't need to do it on save, but I would like something where I don't have to use fzf. That just seems like an extra step. I'd rather go straight to the "organizeImports".

Right now I've done:
```
nnoremap <leader>im :call LanguageClient#textDocument_codeAction()<CR>
```
But this still drops me into the fzf selction UI, which usually only has one selection option. I'd rather have it so that when I do <leader>im it just goes straight to organizing my imports.

**Comment by bartek** [comment] 2020-11-23 17:12
I've been running into this myself and am stuck as @klnusbaum describes, where `organizeImports` is called on buffer write:

    autocmd BufWritePre *.go :call LanguageClient#textDocument_codeAction() "source.organizeImports"

And as others, I have the single-item fzf selection UI. It'd be nice to run `goimports` from gopls on each write. Any help would be appreciated!

**Comment by martskins** [comment] 2020-11-23 19:05
I'm not quite sure as to how to implement this. If `organizeImports` was a command we could just `LanguageClient#workspace_executeCommand`, but it's a code action, not a command, and that `source.organizeImports` is the kind of the code action, so I'm not sure if there can be other code actions with that same kind. If that is the case then filtering by kind could result in unexpected actions being ran.

I tried implementing a `LanguageClient#executeCodeAction` which takes that kind and optional args and that seems to do the trick, but again, not sure if other code actions could potentially share that kind. The `source.organizeImports` is the least confusing one though, the other kinds are a little more 🤷‍♂️ . For example `refactor.rewrite`, not sure what I would expect from that code action without more context.

In any case, what I had in mind was calling the above function like this: `call LanguageClient#executeCodeAction('source.organizeImports')` or `call LanguageClient#executeCodeAction('source.organizeImports', [... additional args ...])`. There are some other challenges though, one of them being that we might need to differentiate that being ran in normal vs visual mode for example, so we'd end up with an additional parameter to that function, or separate that into `LanguageClient#executeNormalCodeAction` and `LanguageClient#executeVisualCodeAction`, which could make things a little more confusing still.

Having said all that, I think it would be a great addition, so if anyone has any ideas on how to go about this or wants to open a PR, that'd be great!

Finally, I suggest opening a new issue for this, so that it doesn't get lost and it's easier to track.
