### ISSUE TITLE
Errors/warnings not appearing on hover

### ISSUE THREAD

**Issue by ticki** [autozimu/LanguageClient-neovim#37] opened 2017-03-30 18:56 UTC
# Description

I have enabled LanguageServer-neovim with RLS. It works to a certain extent: The server runs, the diagnostics/hints show, the goto definition works etc., however when hovering the erroring line with the cursor, the error does not show up.

# Exception

It shows up for less than 200 ms. sometimes (maybe 50%) if I go over the line quickly ~~from up to down (does not work if I go over the line from down and upwards).~~ Turns out it works both directions.

# Setup details

> neovim version

0.1.7 (release build)

> Plugin version (git SHA)

ea2531dcb1091e3e6e14790c7865f567948d341a

> Minimal vimrc.

```vim
call plug#begin('$XDG_CONFIG_HOME/nvim/plugged')
    Plug 'Shougo/deoplete.nvim', { 'do': ':UpdateRemotePlugins' }
    Plug 'Shougo/echodoc.vim'
    Plug 'airblade/vim-gitgutter'
    Plug 'autozimu/LanguageClient-neovim', { 'do': ':UpdateRemotePlugins' }
    Plug 'bling/vim-airline'
    Plug 'cohama/lexima.vim'
    Plug 'kien/ctrlp.vim'
    Plug 'lervag/vimtex'
    Plug 'plasticboy/vim-markdown'
    Plug 'rust-lang/rust.vim'
    Plug 'scrooloose/syntastic'
    Plug 'sjl/badwolf'
    Plug 'ticki/rust-cute-vim'
    Plug 'vim-airline/vim-airline-themes'
call plug#end()

let g:deoplete#enable_at_startup = 1
set completeopt-=preview
let g:LanguageClient_serverCommands = {
    \ 'rust': ['rls'],
\ }

" some stuff ommitted
```

> Content of `:CheckHealth`.

All success.

> Content of `~/.local/share/nvim/rplugin.vim`.

```vim
" python3 plugins
call remote#host#RegisterPlugin('python3', '/home/ticki/.config/nvim/plugged/LanguageClient-neovim/rplugin/python3/LanguageClient', [
      \ {'sync': v:true, 'name': 'LanguageClient_alive', 'type': 'function', 'opts': {}},
      \ {'sync': v:false, 'name': 'LanguageClient_completionItem/resolve', 'type': 'function', 'opts': {}},
      \ {'sync': v:false, 'name': 'LanguageClient_completionManager_refresh', 'type': 'function', 'opts': {}},
      \ {'sync': v:false, 'name': 'LanguageClient_exit', 'type': 'function', 'opts': {}},
      \ {'sync': v:false, 'name': 'LanguageClient_FZFSinkTextDocumentDocumentSymbol', 'type': 'function', 'opts': {}},
      \ {'sync': v:false, 'name': 'LanguageClient_FZFSinkTextDocumentReferences', 'type': 'function', 'opts': {}},
      \ {'sync': v:false, 'name': 'LanguageClient_FZFSinkWorkspaceSymbol', 'type': 'function', 'opts': {}},
      \ {'sync': v:false, 'name': 'CursorMoved', 'type': 'autocmd', 'opts': {'pattern': '*', 'eval': 'line(''.'')'}},
      \ {'sync': v:false, 'name': 'LanguageClient_initialize', 'type': 'function', 'opts': {}},
      \ {'sync': v:false, 'name': 'LanguageClient_registerServerCommands', 'type': 'function', 'opts': {}},
      \ {'sync': v:false, 'name': 'LanguageClient_setLoggingLevel', 'type': 'function', 'opts': {}},
      \ {'sync': v:false, 'name': 'LanguageClientStart', 'type': 'command', 'opts': {}},
      \ {'sync': v:false, 'name': 'LanguageClientStop', 'type': 'command', 'opts': {}},
      \ {'sync': v:false, 'name': 'TextChanged', 'type': 'autocmd', 'opts': {'pattern': '*'}},
      \ {'sync': v:false, 'name': 'TextChangedI', 'type': 'autocmd', 'opts': {'pattern': '*'}},
      \ {'sync': v:false, 'name': 'LanguageClient_textDocument_completion', 'type': 'function', 'opts': {}},
      \ {'sync': v:false, 'name': 'LanguageClient_textDocument_definition', 'type': 'function', 'opts': {}},
      \ {'sync': v:false, 'name': 'LanguageClient_textDocument_didClose', 'type': 'function', 'opts': {}},
      \ {'sync': v:false, 'name': 'BufReadPost', 'type': 'autocmd', 'opts': {'pattern': '*'}},
      \ {'sync': v:false, 'name': 'BufWritePost', 'type': 'autocmd', 'opts': {'pattern': '*'}},
      \ {'sync': v:false, 'name': 'LanguageClient_textDocument_documentSymbol', 'type': 'function', 'opts': {}},
      \ {'sync': v:false, 'name': 'LanguageClient_textDocument_hover', 'type': 'function', 'opts': {}},
      \ {'sync': v:false, 'name': 'LanguageClient_textDocument_references', 'type': 'function', 'opts': {}},
      \ {'sync': v:false, 'name': 'LanguageClient_textDocument_rename', 'type': 'function', 'opts': {}},
      \ {'sync': v:false, 'name': 'LanguageClient_textDocument_signatureHelp', 'type': 'function', 'opts': {}},
      \ {'sync': v:false, 'name': 'LanguageClient_workspace_symbol', 'type': 'function', 'opts': {}},
     \ ])
call remote#host#RegisterPlugin('python3', '/home/ticki/.config/nvim/plugged/deoplete.nvim/rplugin/python3/deoplete', [
      \ {'sync': v:true, 'name': '_deoplete', 'type': 'function', 'opts': {}},
     \ ])
```

> Run `:call LanguageClient_setLoggingLevel('DEBUG')` and then
  `:LanguageClientStart`, reproduce the bug, attach content of
  `/tmp/LanguageClient.log`.

```
20:54:48 INFO     Begin LanguageClientStart
20:54:48 INFO     End LanguageClientStart
20:54:48 INFO     Begin initialize
20:54:48 INFO     rootPath: /home/ticki/code/tfs/core
20:54:48 DEBUG     => {"jsonrpc": "2.0", "method": "initialize", "params": {"processId": 19363, "rootPath": "/home/ticki/code/tfs/core", "rootUri": "file:///home/ticki/code/tfs/core", "capabilities": {}}, "id": 0}
20:54:48 DEBUG     <= 
20:54:48 DEBUG     <= {"jsonrpc":"2.0","id":0,"result":{"capabilities":{"textDocumentSync":2,"hoverProvider":true,"completionProvider":{"resolveProvider":true,"triggerCharacters":[".",":"]},"signatureHelpProvider":{"triggerCharacters":[]},"definitionProvider":true,"referencesProvider":true,"documentHighlightProvider":true,"documentSymbolProvider":true,"workspaceSymbolProvider":true,"codeActionProvider":false,"documentFormattingProvider":true,"documentRangeFormattingProvider":true,"renameProvider":true}}}
20:54:48 INFO     End initialize
20:54:48 DEBUG     <= {"jsonrpc":"2.0","method":"rustDocument/diagnosticsBegin","params":null}
20:54:48 WARNING  no handler implemented for rustDocument_diagnosticsBegin
20:54:48 WARNING  register completion manager source failed.
20:54:48 INFO     textDocument/didOpen
20:54:48 DEBUG     => {"jsonrpc": "2.0", "method": "textDocument/didOpen", "params": {"textDocument": {"uri": "file:///home/ticki/code/tfs/core/src/lib.rs", "languageId": "rust", "version": 1, "text": "//! The TFS library.\n//!\n//! This is the official implementation of the TFS specification. It implements the specification\n//! in its full form, and is accessible as a library.\n\n#![feature(conservative_impl_trait, i128_type, try_from)]\n\n#[macro_use]\nextern crate slog;\n\nextern crate crossbeam;\nextern crate futures;\nextern crate little_endian;\nextern crate lz4_compress;\nextern crate mlcr;\nextern crate rand;\nextern crate ring;\nextern crate ring_pwhash;\nextern crate seahash;\nextern crate speck;\nextern crate thread_object;\n\n#[macro_use]\nmod error;\n#[macro_use]\nmod macros;\n\nmod alloc;\nmod disk;\nmod fs;\n\npub use error::Error;", "last_update": 1490900088.4552875, "dirty": true}}}
```

**Comment by autozimu** [comment] 2017-03-30 19:22
Thanks for reporting. I will look into it some time this week.

**Comment by autozimu** [comment] 2017-04-03 02:17
I don't know if I understand this issue correctly. Are you saying that when you move cursor acrossing lines, the error message shows up and then disappear immediately?

**Comment by ticki** [comment] 2017-04-03 20:26
Yes.

**Comment by autozimu** [comment] 2017-04-03 20:31
If that's the case, then the program is working as expected.

The message are always displayed for current cursor line, as there isn't too much value display the message when the cursor is not on that error line.

This behavior is similar to what [ale](https://github.com/w0rp/ale) does.

**Comment by ticki** [comment] 2017-04-03 20:34
Oh, on "disappear immediately", I meant it disappeared while I am on the line. Within less than 4th of a second.

**Comment by autozimu** [comment] 2017-04-03 20:42
I see. That seems like a bug.

I will first try reproduce it.

**Comment by autozimu** [comment] 2017-04-03 23:24
I cannot reproduce the issue with provided vimrc (BTW, that is not a minimal vimrc).

Also note that, I used a simple sample project and it is working fine.

I've also tried with tfs, but it seems rls cannot handle large projects like that and diagnostic messages took forever to finish, in which case, the problem is not the scope of this project.

**Comment by autozimu** [comment] 2017-08-24 00:46
Closing rotten tickets.

**Closed by autozimu** 2017-08-24 00:46 UTC

**Comment by mattmahn** [comment] 2017-09-18 09:14
I'm having the same issue. Sometimes ALE messages are hidden a fraction of a second after moving to a line with an ALE warning. This happens essentially 100% of the time with my full vimrc, but fairly rarely with this minimal vimrc. Moving the cursor horizontally in the line always show the ALE message.

I tested in the posted minimal vimrc (but I removed whitespace and comments, so line numbers aren't matching). The ALE warning is "Use the full option name 'relativenumber' instead of 'rnu' (see :help option-summary)". I suspect the problem will still arise when removing `set nocompatible` and/or `set rnu`, but it didn't occur in the couple minutes I was trying.

-----

- neovim version: v0.2.0
- Plugin version (git SHA): 88430f5
- Minimal vimrc:
```vim
set nocompatible
call plug#begin('~/.vim/bundle')
Plug 'Shougo/deoplete.nvim', { 'do': ':UpdateRemotePlugins' }
Plug 'autozimu/LanguageClient-neovim', { 'do': ':UpdateRemotePlugins' }
Plug 'Shougo/denite.nvim'
Plug 'w0rp/ale'
call plug#end()
set rnu
```
- Content of `:CheckHealth`.
```

health#deoplete#check
========================================================================
## deoplete.nvim
  - SUCCESS: has("nvim") was successful
  - SUCCESS: has("python3") was successful
  - INFO: If you're still having problems, try the following commands:
    $ export NVIM_PYTHON_LOG_FILE=/tmp/log
    $ export NVIM_PYTHON_LOG_LEVEL=DEBUG
    $ nvim
    $ cat /tmp/log_{PID}
    and then create an issue on github

health#nvim#check
========================================================================
## Configuration
  - SUCCESS: no issues found

## Performance
  - SUCCESS: Build type: Release

## Remote Plugins
  - SUCCESS: Up to date

## terminal
  - INFO: key_backspace (kbs) terminfo entry: key_backspace=^H
  - INFO: key_dc (kdch1) terminfo entry: key_dc=\E[3~

health#provider#check
========================================================================
## Clipboard (optional)
  - SUCCESS: Clipboard tool found: xsel

## Python 2 provider (optional)
  - WARNING: No Python interpreter was found with the neovim module.  Using the first available for diagnostics.
  - WARNING: provider/pythonx: Could not load Python 2:
    /bin/python2 does not have the "neovim" module. :help |provider-python|
    /bin/python2.7 does not have the "neovim" module. :help |provider-python|
    python2.6 not found in search path or not executable.
    /bin/python is Python 3.6 and cannot provide Python 2.
  - ERROR: Python provider error
    - SUGGESTIONS:
      - provider/pythonx: Could not load Python 2:
          /bin/python2 does not have the "neovim" module. :help |provider-python|
          /bin/python2.7 does not have the "neovim" module. :help |provider-python|
          python2.6 not found in search path or not executable.
          /bin/python is Python 3.6 and cannot provide Python 2.
  - INFO: Executable: Not found

## Python 3 provider (optional)
  - INFO: `g:python3_host_prog` is not set.  Searching for python3 in the environment.
  - INFO: Multiple python3 executables found.  Set `g:python3_host_prog` to avoid surprises.
  - INFO: Executable: /bin/python3
  - INFO: Other python executable: /usr/bin/python3
  - INFO: Python3 version: 3.6.2
  - INFO: python3-neovim version: 0.1.13
  - SUCCESS: Latest python3-neovim is installed: 0.1.13

## Ruby provider (optional)
  - INFO: Ruby: ruby 2.4.2p198 (2017-09-14 revision 59899) [x86_64-linux]
  - INFO: Host: /home/matt/.gem/ruby/2.4.0/bin/neovim-ruby-host
  - SUCCESS: Latest "neovim" gem is installed: 0.5.1
```
- Content of `~/.local/share/nvim/rplugin.vim`.
```vim
" python3 plugins
call remote#host#RegisterPlugin('python3', '/home/matt/.vimfiles/vim.symlink/bundle/LanguageClient-neovim/rplugin/python3/LanguageClient', [
      \ {'sync': v:true, 'name': 'LanguageClient_alive', 'type': 'function', 'opts': {}},
      \ {'sync': v:false, 'name': 'LanguageClient_call', 'type': 'function', 'opts': {}},
      \ {'sync': v:false, 'name': 'LanguageClient_completionItem/resolve', 'type': 'function', 'opts': {}},
      \ {'sync': v:false, 'name': 'LanguageClient_completionManager_refresh', 'type': 'function', 'opts': {}},
      \ {'sync': v:false, 'name': 'LanguageClient_exit', 'type': 'function', 'opts': {}},
      \ {'sync': v:false, 'name': 'LanguageClient_FZFSinkTextDocumentDocumentSymbol', 'type': 'function', 'opts': {}},
      \ {'sync': v:false, 'name': 'LanguageClient_FZFSinkTextDocumentReferences', 'type': 'function', 'opts': {}},
      \ {'sync': v:false, 'name': 'LanguageClient_FZFSinkWorkspaceSymbol', 'type': 'function', 'opts': {}},
      \ {'sync': v:true, 'name': 'LanguageClient_getState', 'type': 'function', 'opts': {}},
      \ {'sync': v:false, 'name': 'BufReadPost', 'type': 'autocmd', 'opts': {'pattern': '*', 'eval': '{''languageId'': &filetype, ''filename'': expand(''%:p'')}'}},
      \ {'sync': v:false, 'name': 'BufWritePost', 'type': 'autocmd', 'opts': {'pattern': '*', 'eval': '{''languageId'': &filetype, ''filename'': expand(''%:p'')}'}},
      \ {'sync': v:false, 'name': 'CursorMoved', 'type': 'autocmd', 'opts': {'pattern': '*', 'eval': '[&buftype, line(''.'')]'}},
      \ {'sync': v:false, 'name': 'TextChanged', 'type': 'autocmd', 'opts': {'pattern': '*', 'eval': '{''filename'': expand(''%:p''), ''buftype'': &buftype}'}},
      \ {'sync': v:false, 'name': 'TextChangedI', 'type': 'autocmd', 'opts': {'pattern': '*', 'eval': '{''filename'': expand(''%:p''), ''buftype'': &buftype}'}},
      \ {'sync': v:false, 'name': 'LanguageClient_initialize', 'type': 'function', 'opts': {}},
      \ {'sync': v:false, 'name': 'LanguageClient_notify', 'type': 'function', 'opts': {}},
      \ {'sync': v:false, 'name': 'LanguageClient_registerServerCommands', 'type': 'function', 'opts': {}},
      \ {'sync': v:false, 'name': 'LanguageClient_rustDocument_implementations', 'type': 'function', 'opts': {}},
      \ {'sync': v:false, 'name': 'LanguageClient_setLoggingLevel', 'type': 'function', 'opts': {}},
      \ {'sync': v:false, 'name': 'LanguageClientStart', 'type': 'command', 'opts': {'nargs': '*', 'range': ''}},
      \ {'sync': v:false, 'name': 'LanguageClientStop', 'type': 'command', 'opts': {}},
      \ {'sync': v:false, 'name': 'LanguageClient_textDocument_completion', 'type': 'function', 'opts': {}},
      \ {'sync': v:false, 'name': 'LanguageClient_textDocument_completionOmnifunc', 'type': 'function', 'opts': {}},
      \ {'sync': v:false, 'name': 'LanguageClient_textDocument_definition', 'type': 'function', 'opts': {}},
      \ {'sync': v:false, 'name': 'LanguageClient_textDocument_didClose', 'type': 'function', 'opts': {}},
      \ {'sync': v:false, 'name': 'LanguageClient_textDocument_documentSymbol', 'type': 'function', 'opts': {}},
      \ {'sync': v:false, 'name': 'LanguageClient_textDocument_formatting', 'type': 'function', 'opts': {}},
      \ {'sync': v:false, 'name': 'LanguageClient_textDocument_hover', 'type': 'function', 'opts': {}},
      \ {'sync': v:false, 'name': 'LanguageClient_textDocument_rangeFormatting', 'type': 'function', 'opts': {}},
      \ {'sync': v:false, 'name': 'LanguageClient_textDocument_references', 'type': 'function', 'opts': {}},
      \ {'sync': v:false, 'name': 'LanguageClient_textDocument_rename', 'type': 'function', 'opts': {}},
      \ {'sync': v:false, 'name': 'LanguageClient_textDocument_signatureHelp', 'type': 'function', 'opts': {}},
      \ {'sync': v:false, 'name': 'LanguageClient_workspace_symbol', 'type': 'function', 'opts': {}},
     \ ])
call remote#host#RegisterPlugin('python3', '/home/matt/.vimfiles/vim.symlink/bundle/denite.nvim/rplugin/python3/denite', [
      \ {'sync': v:true, 'name': '_denite_init', 'type': 'function', 'opts': {}},
      \ {'sync': v:true, 'name': '_denite_start', 'type': 'function', 'opts': {}},
      \ {'sync': v:true, 'name': '_denite_do_action', 'type': 'function', 'opts': {}},
     \ ])
call remote#host#RegisterPlugin('python3', '/home/matt/.vimfiles/vim.symlink/bundle/deoplete.nvim/rplugin/python3/deoplete', [
      \ {'sync': v:false, 'name': '_deoplete', 'type': 'function', 'opts': {}},
     \ ])


" ruby plugins


" python plugins
```
- Run `:call LanguageClient_setLoggingLevel('DEBUG')` and then
  `:LanguageClientStart`, reproduce the bug, attach content of
  `/tmp/LanguageClient.log`:
```
04:02:48 DEBUG   [MainThread] state.last_cursor_line: 12 => 13
04:02:48 DEBUG   [MainThread] state.last_cursor_line: 13 => 14
04:02:51 DEBUG   [MainThread] state.last_cursor_line: 14 => 13
04:02:51 DEBUG   [MainThread] state.last_cursor_line: 13 => 14
04:02:51 DEBUG   [MainThread] state.last_cursor_line: 14 => 13
04:02:51 DEBUG   [MainThread] state.last_cursor_line: 13 => 14
04:02:52 DEBUG   [MainThread] state.last_cursor_line: 14 => 13
04:02:52 DEBUG   [MainThread] state.last_cursor_line: 13 => 14
04:02:52 DEBUG   [MainThread] state.last_cursor_line: 14 => 13
04:02:52 DEBUG   [MainThread] state.last_cursor_line: 13 => 14
04:02:53 DEBUG   [MainThread] state.last_cursor_line: 14 => 13
04:02:53 DEBUG   [MainThread] state.last_cursor_line: 13 => 14
04:02:53 DEBUG   [MainThread] state.last_cursor_line: 14 => 13
04:02:53 DEBUG   [MainThread] state.last_cursor_line: 13 => 14
04:02:54 DEBUG   [MainThread] state.last_cursor_line: 14 => 13
04:02:54 DEBUG   [MainThread] state.last_cursor_line: 13 => 14
04:02:54 DEBUG   [MainThread] state.last_cursor_line: 14 => 13
04:02:54 DEBUG   [MainThread] state.last_cursor_line: 13 => 14
04:02:54 DEBUG   [MainThread] state.last_cursor_line: 14 => 13
04:02:54 DEBUG   [MainThread] state.last_cursor_line: 13 => 14
04:02:55 DEBUG   [MainThread] state.last_cursor_line: 14 => 13
04:02:55 DEBUG   [MainThread] state.last_cursor_line: 13 => 14
04:02:55 DEBUG   [MainThread] state.last_cursor_line: 14 => 13
04:02:55 DEBUG   [MainThread] state.last_cursor_line: 13 => 14
04:02:56 DEBUG   [MainThread] state.last_cursor_line: 14 => 13
04:02:56 DEBUG   [MainThread] state.last_cursor_line: 13 => 14
04:02:56 DEBUG   [MainThread] state.last_cursor_line: 14 => 13
04:02:56 DEBUG   [MainThread] state.last_cursor_line: 13 => 14
04:02:56 DEBUG   [MainThread] state.last_cursor_line: 14 => 13
04:02:56 DEBUG   [MainThread] state.last_cursor_line: 13 => 14
04:03:03 DEBUG   [MainThread] state.last_cursor_line: 14 => 13
04:03:03 DEBUG   [MainThread] state.last_cursor_line: 13 => 14
04:03:03 DEBUG   [MainThread] state.last_cursor_line: 14 => 13
04:03:03 DEBUG   [MainThread] state.last_cursor_line: 13 => 14
04:03:03 DEBUG   [MainThread] state.last_cursor_line: 14 => 13
04:03:03 DEBUG   [MainThread] state.last_cursor_line: 13 => 14
04:03:04 DEBUG   [MainThread] state.last_cursor_line: 14 => 13
04:03:04 DEBUG   [MainThread] state.last_cursor_line: 13 => 14
04:03:04 DEBUG   [MainThread] state.last_cursor_line: 14 => 13
04:03:04 DEBUG   [MainThread] state.last_cursor_line: 13 => 14
04:03:05 DEBUG   [MainThread] state.last_cursor_line: 14 => 13
04:03:05 DEBUG   [MainThread] state.last_cursor_line: 13 => 14
04:03:05 DEBUG   [MainThread] state.last_cursor_line: 14 => 13
04:03:05 DEBUG   [MainThread] state.last_cursor_line: 13 => 14
```
(literally just me moving the the cursor up & down in the minimal vimrc until the ALE warning is not displayed when on the correct line)

**Comment by autozimu** [comment] 2017-09-18 16:38
I am guessing when you said "ALE message", you meant "diagnostic message" from this plugin.

One thing to note is that if you have ALE/neomake installed and activated, it might conflict with this plugin.

I've tried locally a few more times and still couldn't reproduce.

Sorry but I cannot help much if there isn't sufficient information.

**Comment by autozimu** [comment] 2017-09-18 17:13
I suspect it is possible of a conflict with other plugins.

As far as I know, both ALE and neomake, as well as this plugin, will listen to `CursorMoved` event to show message in the command area. The problem is in vim/neovim there is no way to specify order for event handlers, so it might be the event handlers override each other's side effects, i.e., showing message.

**Comment by mattmahn** [comment] 2017-09-18 20:13
After updating to e3cdf2c569e12a8d4df9c6a13ef058bc822c1f97, I no longer have any issues.

**Comment by autozimu** [comment] 2017-09-18 21:02
nice!
