### ISSUE TITLE
Language server is not running for:

### ISSUE THREAD

**Issue by aeruhxi** [autozimu/LanguageClient-neovim#309] opened 2018-02-07 06:02 UTC
I am reporting a bug.

- NVIM v0.2.2
- commit SHA: 71e75d9cb2c2901672f0fda
- [minimal vimrc](https://pastebin.com/Sck6uXAw)
- [language server](https://github.com/haskell/haskell-ide-engine)
- Reproduction steps (from clean state)
    1. Install haskell-ide-engine according to its instructions (i.e stack install)
    2. open any haskell file in neovim
    3. run `:call LanguageClient_textDocument_hover()`
 
I got `Language server is not running for: haskell`.

## Logs
[/tmp/LanguageClient.log](https://pastebin.com/PC0wiyU4)
`/tmp/LanguageServer.log` is empty

## HIE
`hie --lsp`  works in the terminal
```
λ. hie --lsp
2018-02-07 11:45:34.42836949 [ThreadId 4] - Setting home directory:/home/absolutezero
2018-02-07 11:45:34.429265746 [ThreadId 4] - run entered for HIE Version 0.1.0.0, Git revision 4f2173963b14cb7603bc0c1ce731dc07ac1b7feb (dirty) (1183 commits) x86_64 ghc-8.2.2
2018-02-07 11:45:34.430332663 [ThreadId 4] - Current directory:/home/absolutezero
```

# UPDATE
When I do `:LanguageClientStart`, I get `Not a directory (os error 20)`

**Comment by aeruhxi** [comment] 2018-02-08 02:14
I tried with rust too and got the same problem

**Comment by autozimu** [comment] 2018-02-22 00:39
Can you try with rust language server and paste logs again?

**Comment by aeruhxi** [comment] 2018-02-22 06:42
## LanguageClient.log
```
2018-02-22T12:10:29.899042687+05:45 WARN languageclient::languageclient - Not a directory (os error 20)
2018-02-22T12:10:55.008843727+05:45 ERROR languageclient::languageclient - Error handling message. Message: {"id": 1, "jsonrpc": "2.0", "method": "languageClient/startServer", "params": {"cmdargs": [], "languageId": "rust", "buftype": "", "filename": "/home/absolutezero/LanguageClient-neovim/tests/data/sample-rs/src/main.rs"}}. Error: Err(Error { repr: Os { code: 20, message: "Not a directory" } })
```
## LanguageServer.log 
empty

## vimrc
```
" Automatically start language servers.
let g:LanguageClient_autoStart = 1

let g:LanguageClient_serverCommands = {
    \ 'haskell': ['hie', '--lsp'],
    \ 'rust': ['rustup', 'run', 'stable', 'rls'],
    \ }
```

**Comment by autozimu** [comment] 2018-02-22 21:43
Thanks for the response.

I cannot reproduce this issue locally. So might need more favor from you.

Could you run `export RUST_BACKTRACE=full` in your terminal, do the same thing and get back with logs?

**Comment by aeruhxi** [comment] 2018-02-23 13:58
## LanguageClient.log
```
2018-02-23T19:41:10.985446429+05:45 WARN languageclient::languageclient - Not a directory (os error 20)
2018-02-23T19:41:16.082836195+05:45 ERROR languageclient::languageclient - Error handling message. Message: {"id": 1, "jsonrpc": "2.0", "method": "languageClient/startServer", "params": {"cmdargs": [], "languageId": "rust", "buftype": "", "filename": "/home/absolutezero/LanguageClient-neovim/tests/data/sample-rs/src/libs.rs"}}. Error: Err(Error { repr: Os { code: 20, message: "Not a directory" } }

stack backtrace:
   0:           0x645e0c - backtrace::backtrace::trace::hcb83ea28a5861f61
   1:           0x645e42 - backtrace::capture::Backtrace::new_unresolved::hc7089655a7becb73
   2:           0x6453cc - failure::backtrace::Backtrace::new::hcd0e5c494e2a0594
   3:           0x53bc0a - <alloc::arc::Arc<std::sync::mutex::Mutex<languageclient::types::State>> as languageclient::languageclient::ILanguageClient>::languageClient_startServer::h39de3ebfd065345f
   4:           0x4bc777 - <alloc::arc::Arc<std::sync::mutex::Mutex<languageclient::types::State>> as languageclient::languageclient::ILanguageClient>::handle_message::h20851d4bdf2c16d5
   5:           0x4424c6 - std::sys_common::backtrace::__rust_begin_short_backtrace::h9e799abeb3823139
   6:           0x4443cd - std::panicking::try::do_call::hcaad138bde864989
   7:           0x6d2f4e - panic_unwind::__rust_maybe_catch_panic
                        at /checkout/src/libpanic_unwind/lib.rs:101
   8:           0x459d07 - <F as alloc::boxed::FnBox<A>>::call_box::haa08234c00c867f0
   9:           0x6c958b - alloc::boxed::{{impl}}::call_once<(),()>
                        at /checkout/src/liballoc/boxed.rs:772
                         - std::sys_common::thread::start_thread
                        at /checkout/src/libstd/sys_common/thread.rs:24
                         - std::sys::imp::thread::{{impl}}::new::thread_start
                        at /checkout/src/libstd/sys/unix/thread.rs:90)
```

**Comment by aeruhxi** [comment] 2018-02-26 14:44
Sorry to bother but just wanted to know if you have got any new findings. Also, what could `Not a directory` mean?

**Comment by autozimu** [comment] 2018-02-26 17:22
No. I cannot reproduce locally nor comprehend what happened of not
directory.

**Comment by autozimu** [comment] 2018-02-28 05:13
Can you follow those steps to get more info about the bug?

1. Put those lines in your vimrc
```vim
let g:LanguageClient_devel = 1 " Use rust debug build
let g:LanguageClient_loggingLevel = 'DEBUG' " Use highest logging level
```
2. Make a debug release of this project by running `make build`
3. Reproduce as usual

I'm running out of idea of what could go wrong in your case. Let me know if you need further help.

**Comment by aeruhxi** [comment] 2018-03-01 05:30
> Make a debug release of this project by running make build

Did you mean clone this project, `make build` and copy it in `~/.vim/plugged/`?

**Comment by autozimu** [comment] 2018-03-01 05:41
> Did you mean clone this project, make build and copy it in ~/.vim/plugged/

No, I mean change directory to your local copy of this plugin (should be `~/.local/share/nvim/plugged/LanguageClient-neovim`), and run `make build`.

**Comment by aeruhxi** [comment] 2018-03-01 06:33
```
let g:LanguageClient_devel = 1 " Use rust debug build
```
After `make build` and putting this line, I got `LanguageClient: Not executable!`

**Comment by autozimu** [comment] 2018-03-01 07:37
Then inside plugin directory, run
```
cp -f target/debug/languageclient bin/
```

And remove that line from your config.

**Comment by aeruhxi** [comment] 2018-03-01 14:31
Looks like I had two copies of plugin in both `~/.vim/plugged/` and `~/.local/share/nvim/plugged/`. But the neovim was actually using the former. So I ran `make build` on the former (instead of the latter which I did at first) and with the line `let g:LanguageClient_devel = 1 " Use rust debug build` added, now it is working. :tada:

**Comment by autozimu** [comment] 2018-03-01 18:04
Were you able to reproduce this issue described error and get the full logs?

**Comment by aeruhxi** [comment] 2018-03-02 00:59
Following those steps, I did not get any error. Plugin is working properly now.

**Comment by autozimu** [comment] 2018-03-02 03:34
OK. Will close this issue for now. Feel free to reopen when you come across it again.

**Closed as completed by autozimu** 2018-03-02 03:34 UTC

**Comment by adamki** [comment] 2018-04-10 06:18
Having issues with install process. 

Here is my minimal `init.vim`:

```
" Setup Plug  --------------------------------------------------------------{{{

  call plug#begin('~/.local/share/nvim/plugged')
  " appearance - search - syntax - italix

  " colors
  Plug 'autozimu/LanguageClient-neovim', {
      \ 'branch': 'next',
      \ 'do': 'bash install.sh',
      \ }

  call plug#end()

" }}}

" Required for operations modifying multiple buffers like rename.
set hidden

let g:LanguageClient_serverCommands = {
    \ 'rust': ['rustup', 'run', 'nightly', 'rls'],
    \ 'javascript': ['javascript-typescript-stdio'],
    \ 'javascript.jsx': ['javascript-typescript-stdio'],
    \ }

nnoremap <silent> K :call LanguageClient#textDocument_hover()<CR>
nnoremap <silent> gd :call LanguageClient#textDocument_definition()<CR>
```

I've run `nvim +PlugInstall +UpdateRemotePlugins +qa` per the instructions and receive no errors. 

ive tried js, jsx and rust files and for each i get the error `Language server is not running for:`


##### Troubleshooting efforts:
Further, I've also included the following lines that you provided earlier:
```
let g:LanguageClient_devel = 1 " Use rust debug build
let g:LanguageClient_loggingLevel = 'DEBUG' " Use highest logging level
```
Ive then gone to `~/.local/share/nvim/plugged/LanguageClient-neovim` and run `make build`

output is below is many many complied packages...and at the end it prints:
` Finished dev [unoptimized + debuginfo] target(s) in 44.88 secs`

**Comment by autozimu** [comment] 2018-04-10 06:55
Make sure you've installed corresponding language servers.

E.g., when you run `javascript-typescript-stdio` in shell, there shouldn't be any error reported.

**Comment by adamki** [comment] 2018-04-10 18:48
not sure how i fixed it.. but i reinstalled nvim last night and was about to forget about this plugin completely. 

This morning... on a whim.. I threw it in my nvim again and it works. The only change i made was removing `delimitmate` plugin and switching to `auto-pairs`.

**Comment by viniarck** [comment] 2018-06-16 17:31
I just stumbled upon this issue of `Not a directory (os error 20)` with pyls, and it's weird since LanguageClient was working fine with go-langserver. To solve this I had to `make build` and set this on my config:

```
let g:LanguageClient_devel = 1 " Use rust debug build
```

@autozimu, FYI, this was the minimal config to reproduce:

```
" Dein auto bootstrap
if (!isdirectory(expand("$HOME/.config/nvim/repos/github.com/Shougo/dein.vim")))
  call system(expand("mkdir -p $HOME/.config/nvim/repos/github.com"))
  call system(expand("git clone https://github.com/Shougo/dein.vim $HOME/.config/nvim/repos/github.com/Shougo/dein.vim"))
endif
set runtimepath+=~/.config/nvim/repos/github.com/Shougo/dein.vim/

call dein#begin(expand('~/.config/nvim'))
call dein#add('Shougo/dein.vim')

" Fuzzy Finder, Interfaces, Navigation -------------------------------------------
call dein#add('junegunn/fzf', { 'build': './install --all', 'merged': 0 })
call dein#add('junegunn/fzf.vim', { 'depends': 'fzf' })
call dein#add('Shougo/denite.nvim')
call dein#add('autozimu/LanguageClient-neovim', { 'build': 'bash install.sh', 'rev': 'next' })

if dein#check_install()
  call dein#install()
endif

call dein#end()

filetype plugin indent on
syntax on

let g:dein#enable_notification = 1
let g:dein#install_progress_type="tabline"
let g:dein#install_message_type="none"
```

**Comment by AlessioGiambrone** [comment] 2020-06-30 13:27
In my case the error was raised because the server for _another_ language wasn't present.
Commenting it out made everything work.
