### ISSUE TITLE
Gutter icons don't update properly with file changes

### ISSUE THREAD

**Issue by YaLTeR** [autozimu/LanguageClient-neovim#725] opened 2019-02-05 07:21 UTC
## Describe the bug
When you change the file with errors or warnings the gutter icons don't update correctly.

## Environment
- neovim/vim version (`nvim --version` or `vim --version`): NVIM v0.3.4
- This plugin version (`git rev-parse --short HEAD`): 1db273f
- This plugin's binary version (`bin/languageclient --version`): `languageclient 0.1.137`
- Minimal vimrc content (A minimal vimrc is the smallest vimrc that could
  reproduce the issue. Refer to an example [here][min-vimrc.vim]): `min-vimrc.vim` but with nightly RLS and with this appended:
```rust
let g:LanguageClient_loadSettings = 1
let g:LanguageClient_settingsPath = '~/.config/nvim/langserver_settings.json'
```
`langserver_settings.json`:
```json
{
        "rust": {
                "clippy_preference": "on",
                "wait_to_build": 500,
                "build_on_save": true
        }
}
```
Build on save helps illustrate the issue better.
- Language server link and version: `rls-preview 1.31.6 (ae0d89a 2019-01-13)`

## To Reproduce
1. `cargo new temp`
1. `nvim -u min-vimrc.vim src/main.rs`
1. Type some random text before the first line, save, observe:
![image](https://user-images.githubusercontent.com/1794388/52258181-24da5180-292f-11e9-9cb9-da72437aecc4.png)
1. Delete the second line, observe that the × icon did not disappear as it should have:
![image](https://user-images.githubusercontent.com/1794388/52258208-3ae81200-292f-11e9-871f-8c1a1c03d868.png)
1. Undo, the × icon is still there, now on the wrong line:
![image](https://user-images.githubusercontent.com/1794388/52258218-4afff180-292f-11e9-8be1-79442dd0a54b.png)
1. Save the file, the × icon is still there, moreover a new × for the error did not appear:
![image](https://user-images.githubusercontent.com/1794388/52258246-61a64880-292f-11e9-9a09-9534eb2a2596.png)

**Comment by autozimu** [comment] 2019-02-12 00:47
Can you double check if this is still the case? I cannot reproduce it locally.

**Comment by YaLTeR** [comment] 2019-02-12 05:49
Still reproduces on 8eba06b `languageclient 0.1.139`.

**Comment by autozimu** [comment] 2019-02-12 06:33
I did observe some behaviour here, that is, changing itself won't trigger diagnostics update, only an explicit write will do. But I can only reproduce it on a linux machine.

This does look like like an rls issue to me, since it isn't reproducible with other language servers.

**Comment by YaLTeR** [comment] 2019-02-12 06:39
Shouldn't the language client / nvim itself delete the gutter icon when the corresponding line is deleted?

**Comment by autozimu** [comment] 2019-02-12 06:53
Firstly, vim signs are associated with line numbers, not line contents.

Signs are lazy updated until language server publishes new diagnostics. If
we delete or update the gutter whenever the line is changed, what about the
case user actively editing content?

**Comment by YaLTeR** [comment] 2019-02-12 07:18
If the user is editing the line then the icon should stay. If the line is deleted though (not like `0D`, but like `dd`) then, I think, it only makes sense to delete the gutter icon because the line it was related to is now gone—just like the corresponding virtual text is deleted.

**Comment by horta** [comment] 2019-02-12 12:30
I have the same problem with python language server. After a while, my gutter will have many warnings signs that don't corresponde to any warning. I'm on macos.

```
NVIM v0.3.4
Build type: Release
LuaJIT 2.0.5
Compilation: /usr/local/Homebrew/Library/Homebrew/shims/mac/super/clang -Wconversion -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1 -DNDEBUG -DMIN_LOG_LEVEL=3 -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wimplicit-fallthrough -Wvla -fstack-protector-strong -fdiagnostics-color=auto -DINCLUDE_GENERATED_DECLARATIONS -D_GNU_SOURCE -DNVIM_MSGPACK_HAS_FLOAT32 -DNVIM_UNIBI_HAS_VAR_FROM -I/tmp/neovim-20190113-94620-d8vv4n/neovim-0.3.4/build/config -I/tmp/neovim-20190113-94620-d8vv4n/neovim-0.3.4/src -I/usr/local/include -I/usr/local/opt/gettext/include -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.14.sdk/usr/include -I/tmp/neovim-20190113-94620-d8vv4n/neovim-0.3.4/build/src/nvim/auto -I/tmp/neovim-20190113-94620-d8vv4n/neovim-0.3.4/build/include
Compiled by brew@Mojave.local

Features: +acl +iconv +jemalloc +tui
See ":help feature-compile"

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/usr/local/Cellar/neovim/0.3.4/share/nvim"

Run :checkhealth for more info
```

This might be relevated to debug:

```
2019-02-12 12:28:51,262 UTC - INFO - pyls.python_ls - Server capabilities: {'codeActionProvider': True, 'codeLensProvider': {'resolveProvider': False}, 'completionProvider': {'resolveProvider': False, 'triggerCharacters': ['.']}, 'documentFormattingProvider': True, 'documentHighlightProvider': True, 'documentRangeFormattingProvider': True, 'documentSymbolProvider': True, 'definitionProvider': True, 'executeCommandProvider': {'commands': []}, 'hoverProvider': True, 'referencesProvider': True, 'renameProvider': True, 'signatureHelpProvider': {'triggerCharacters': ['(', ',']}, 'textDocumentSync': 2, 'experimental': {}}
2019-02-12 12:28:51,263 UTC - ERROR - pyls_jsonrpc.endpoint - Failed to handle notification textDocument/didClose: {'textDocument': {'uri': 'file:///Users/horta/code/horta/limix/limix/io/_fetch.py'}}
Traceback (most recent call last):
  File "/usr/local/anaconda3/lib/python3.7/site-packages/pyls_jsonrpc/endpoint.py", line 142, in _handle_notification
    handler_result = handler(params)
  File "/usr/local/anaconda3/lib/python3.7/site-packages/pyls_jsonrpc/dispatchers.py", line 23, in handler
    return method(**(params or {}))
  File "/usr/local/anaconda3/lib/python3.7/site-packages/pyls/python_ls.py", line 232, in m_text_document__did_close
    self.workspace.rm_document(textDocument['uri'])
  File "/usr/local/anaconda3/lib/python3.7/site-packages/pyls/workspace.py", line 74, in rm_document
    self._docs.pop(doc_uri)
KeyError: 'file:///Users/horta/code/horta/limix/limix/io/_fetch.py'
```

**Comment by autozimu** [comment] 2019-02-13 00:09
In a sense, this plugin is dumb in that it doesn't understand what changes are actually made by user. It relies on information published by language server.

I believe that's also the main biggest advantage of LSP such that all of the little details are pushed to 
server.

Back to the original issue, it's pretty clear now that it is a rls issue. Closing.

**Closed as completed by autozimu** 2019-02-13 00:09 UTC

**Comment by autozimu** [comment] 2019-02-13 00:11
@horta This specific error comes from language server. Please file issue or PR at language server side.

If it is still an issue of this client, please file issue following template.
