### ISSUE TITLE
call LanguageClient_startServer() error

### ISSUE THREAD

**Issue by wells-xu** [autozimu/LanguageClient-neovim#208] opened 2017-12-12 12:16 UTC
## vim-plug status:
Finished. 0 error(s).  
[=]                              
- LanguageClient-neovim: OK 

## neovim version
- NVIM v0.2.2 (brew install neovim && pip install neovim)
- OS:  mackOS High Sierra 10.13.1
## init.vim
```
call plug#begin('~/.local/share/nvim/plugged')
Plug 'autozimu/LanguageClient-neovim', { 'branch': 'next', 'do': './install.sh' }
call plug#end()
---
autocmd BufReadPost *.rs setlocal filetype=rust
let g:loaded_python3_provider = 1
let g:LanguageClient_serverCommands = {
    \ 'rust': ['rustup', 'run', 'nightly', 'rls'],
    \ }
```
## Reproduction steps (from clean state)
```
- when I open nvim and input command: call LanguageClient_startServer()
- error found: (so I can't use normal cpp LSP service at all)
处理 function LanguageClient_startServer[1]..LanguageClient#Call[8]..LanguageClient#Write 时发生错误:                                                                                                                                                              
第    3 行:
E900: Invalid job id
```
- checkhealth: ok(no error)
## Any command below not work as same error print above.
- call LanguageClient_setLoggingLevel('DEBUG'
- LanguageClientStart

**Comment by autozimu** [comment] 2017-12-18 20:34
Could you run a test by running the languageclient directly by
```
cd YOUR_PLUGIN_FOLDER
bin/languageclient --version
bin/languageclient
```
And paste the output here.

**Comment by softinio** [comment] 2017-12-22 01:06
I am having the same issue. I don't know which `bin` directory you want but if its this one: `~/.vim/plugged/LanguageClient-neovim/bin` its completely empty with nothing in it. 

How do you enable more debug?  Thx!

**Comment by autozimu** [comment] 2017-12-22 01:14
If the folder is empty, you probably missed some steps in https://github.com/autozimu/LanguageClient-neovim/blob/next/INSTALL.md#3-install-this-plugin

Specially, you could run `./install.sh`  or `./install.ps1` to get prebuild binary.

**Comment by softinio** [comment] 2017-12-22 02:11
I followed what you suggested and the file is now there so its version is: 

```
languageclient 0.1.2 (6f10d7ffff22bfa36df972276e2783b199117ea9 2017-12-22T02:07:52.649520Z)
```

It still doesn't work for me. Does this need to be added to my path in my shell? 

Also note in my config I had followed the instructions in your README from master branch originally and didnt realize it changed. I tried the README on next branch and note install.sh fails as download link doesn't work or exist it gives a 404. 

Using the above link it worked in having the binary in the bin directory I mentioned.

But I still get the error mentioned and LSP doesnt work for me. 

ps: Thanks for responding fast.

**Comment by autozimu** [comment] 2017-12-22 02:15
Could you run `:LanguageClientStart` and paste the error message here?

**Comment by softinio** [comment] 2017-12-22 03:28
yup here it is: 

```
Error detected while processing function LanguageClient_startServer[8]..LanguageClient#Call[8]..LanguageClient#Writ
e:
line    3:
E900: Invalid job id
Press ENTER or type command to continue
```

**Comment by softinio** [comment] 2017-12-22 04:13
How can I enable more debug logging or debug this plugin? Maybe I can help fix and contribute to your project.

**Comment by autozimu** [comment] 2017-12-22 04:48
Could you check if there  is any content in `/tmp/LanguageClient.log` and `/tmp/LanguageServer.log`?

**Comment by autozimu** [comment] 2017-12-22 04:56
In order to turn on full debug output, you will need to have
```
let $LANGUAGECLIENT_DEBUG=1
let g:LanguageClient_loggingLevel='DEBUG'
let g:LanguageClient_autoStart=0
```
inside vimrc.

Make a debug build by running
```
make build
```
inside this project directory.

And then open a file and run `:LanguageClientStart`. `/tmp/LanguageClient.log` and `/tmp/LanguageServer.log` should have detailed logs.

**Comment by softinio** [comment] 2017-12-22 05:42
Client log: 

```
cat  /tmp/LanguageClient.log
2017-12-22T00:41:23.931533-05:00 WARN languageclient::languageclient - Some arguments are missing, requesting from vim. Keys: ["rootPath"]. Exps: ["v:null"]
2017-12-22T00:41:23.933158-05:00 WARN languageclient::utils - Unknown project type. Fallback to use dir as project root: Ok("/Users/salar.rahmanian/projects/match.thespis.common/src/main/scala/com/snagajob/thespis/common/client/search")
2017-12-22T00:41:24.020389-05:00 ERROR languageclient::languageclient - Error handling message. Message: {"id": 7, "jsonrpc": "2.0", "method": "languageClient/startServer", "params": {"cmdargs": [], "languageId": "scala", "buftype": "", "filename": "/Users/salar.rahmanian/projects/match.thespis.common/src/main/scala/com/snagajob/thespis/common/client/search/SearchClient.scala"}}. Error: Err(ErrorImpl { code: Message("invalid type: map, expected u8"), line: 0, column: 0 })
```

Server log nothing in file.

**Comment by softinio** [comment] 2017-12-22 15:10
@autozimu I enabled more debug on LSP Server I am using with this and I get: 

```
[debug] Unhandled notification received: textDocument/didChange
[debug] onRequestMessage: JsonRpcRequestMessage(2.0, 9, textDocument/hover, {"position":{"character":14,"line":30},"textDocument":{"uri":"file:///Users/salar.rahmanian/projects/match.thespis.common/src/main/scala/com/snagajob/thespis/common/client/search/SearchClient.scala"}}})
```

Is the issue this server uses v2 of the protocol and this plugin is v3 you think?

**Comment by softinio** [comment] 2017-12-23 01:46
@autozimu think I have figured it out I need to add for my `scala` LSP Server support to: 

https://github.com/autozimu/LanguageClient-neovim/blob/next/src/utils.rs#L14

Will try to fix it myself and do a PR for you to contribute to this project.

**Comment by softinio** [comment] 2017-12-24 14:48
@autozimu 

```
2017-12-23T08:52:51.148914-05:00 ERROR languageclient::languageclient - Error handling message. Message: {"id": 3, "jsonrpc": "2.0", "method": "languageClient/startServer", "params": {"cmdargs": [], "languageId": "scala", "buftype": "", "filename": "/Users/salar.rahmanian/projects/match.thespis.common/src/main/scala/com/snagajob/thespis/common/client/search/SearchClient.scala"}}. Error: Err(ErrorImpl { code: Message("invalid type: map, expected u8"), line: 0, column: 0 })
2017-12-23T08:52:51.149077-05:00 INFO languageclient::languageclient - => {"jsonrpc":"2.0","error":{"code":-32603,"message":"invalid type: map, expected u8"},"id":3}
```
Can you spot whats causing this error? what should be a u8?

**Comment by autozimu** [comment] 2017-12-24 17:13
Could you provide complete debug level logs?

Rather than ping back and forth information here, I’d appreciate if you can
follow the issue template to fill in reproduction requirements.

**Comment by softinio** [comment] 2017-12-24 23:29
Client: 

https://gist.github.com/softinio/3bdedb14f0515dc9aed867a846743bcf

Server is blank.

All other details exact same as original creator of this issue.  Thanks!

Happy to help with fix/pr if you can point me to right direction as new to LSP etc

Thanks.

**Comment by Anrock** [comment] 2017-12-27 17:02
Not sure if i have same issue, but also includes `"invalid type: map, expected u8"` error: #238

**Comment by softinio** [comment] 2017-12-29 14:05
@Anrock yup looks like the same issue thanks for pointing out

**Comment by autozimu** [comment] 2018-01-02 05:22
Should be fixed by https://github.com/autozimu/LanguageClient-neovim/commit/5e876095e98f5b782f4d1259e5b397bfd14547da

**Closed by autozimu** 2018-01-02 05:22 UTC
