### ISSUE TITLE
deoplete python argument completion breaks my typing flow

### ISSUE THREAD

**Issue by robertsawko** [autozimu/LanguageClient-neovim#737] opened 2019-02-17 15:04 UTC
Hi,

I am struggling with a minor incovenience with completion. It's likely this is actually a feature rather than a bug, I wasn't able to sort it out yet.

## Describe the bug

Simply, when I complete a function which has arguments I get explicit placeholders and I couldn't find a way to rewind through them e.g.:

```python
curves.append(${1:object})$0
```
I would expect either no placeholders like in vanilla deoplete or some way to jump through various arguments until all placeholders are gone without leaving Insert mode.

## Environment
- neovim/vim version (`nvim --version` or `vim --version`):
```shell
NVIM v0.3.4
Build type: Release
LuaJIT 2.0.5
Compilation: /usr/bin/cc -march=x86-64 -mtune=generic -O2 -pipe -fstack-protector-strong -fno-plt -Wconversion -O2 -DNDEBUG -DMIN_LOG_LEVEL=3 -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wimplicit-fallthrough -Wvla -fstack-protector-strong -fdiagnostics-color=auto -Wno-array-bounds -DINCLUDE_GENERATED_DECLARATIONS -D_GNU_SOURCE -DNVIM_MSGPACK_HAS_FLOAT32 -DNVIM_UNIBI_HAS_VAR_FROM -I/build/neovim/src/build/config -I/build/neovim/src/neovim-0.3.4/src -I/usr/include -I/build/neovim/src/build/src/nvim/auto -I/build/neovim/src/build/include
Compiled by builduser

Features: +acl +iconv +jemalloc +tui 
See ":help feature-compile"

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/usr/share/nvim"

```

- This plugin version (`git rev-parse --short HEAD`):`ab1644f`
- This plugin's binary version (`bin/languageclient --version`): `0.1.140`
- Minimal vimrc content (A minimal vimrc is the smallest vimrc that could
  reproduce the issue. Refer to an example [here][min-vimrc.vim]):
```
call plug#begin('~/.config/nvim/mini-python')

Plug 'autozimu/LanguageClient-neovim', {
    \ 'branch': 'next',
    \ 'do': 'bash install.sh',
    \ }

Plug 'Shougo/deoplete.nvim', {
    \ 'do': ':UpdateRemotePlugins' }

Plug 'zchee/deoplete-jedi'

call plug#end()

let g:deoplete#enable_at_startup = 1

let g:LanguageClient_serverCommands = {
    \ 'python': ['/usr/bin/pyls'],
    \ }


let $RUST_BACKTRACE = 1
let g:LanguageClient_loggingLevel = 'INFO'
let g:LanguageClient_loggingFile =  expand('~/.local/share/nvim/LanguageClient.log')
let g:LanguageClient_serverStderr = expand('~/.local/share/nvim/LanguageServer.log')

```
- Language server link and version: `python-language-server==0.23.2`

## To Reproduce

1. Create/Fetch example project ...
1. Start vim, `nvim -u min-vimrc.vim` ...
1. Edit
```python
my_list = [1, 2, 3]
my_list.app<Tab>

## Current behavior
As above, I get function name and placeholders.

## Expected behavior

Either suppress placeholders or a way to navigate and fill them without leaving Insert mode.

**Comment by Shougo** [comment] 2019-02-18 00:04
https://github.com/Shougo/deoplete.nvim/issues/940#issuecomment-464530533

**Comment by mkoura** [comment] 2019-02-19 09:37
I have the same issue and the solution described in https://github.com/Shougo/deoplete.nvim/issues/940 by @Shougo doesn't solve it. It's `let g:LanguageClient_hasSnippetSupport = 0` ("Snippet" vs "Snippets"), but the placeholders are there regardless if I set it to 0 or not.

**Comment by robertsawko** [comment] 2019-02-19 10:33
Yes, @mkoura same here. Doesn't solve it.

Also I am normally using [ultisnips](https://github.com/sirver/UltiSnips) for my snippets so I was wondering if this can be integrated. Placeholders aren't bad. It's just how you navigate them? I am used to them for for-loops but very extensively in TeX. It would be nice to have them in `numpy` and more complex libraries.

**Comment by mkoura** [comment] 2019-02-19 11:12
@robertsawko It turns out this is caused by https://github.com/palantir/python-language-server/pull/499/
Having
```json
{
    "pyls": {
        "plugins": {
            "jedi_completion": {
                "include_params": false
            }
        }
    }
}
```
in my `settings.json` solves this.

**Comment by Shougo** [comment] 2019-02-19 23:33
I think it should be fixed in LanguageClient-neovim side.
candidates' word should not included snippet placeholder.
snippet is already included in userdata.snippets field.

The current behavior is useless.

**Comment by robertsawko** [comment] 2019-02-19 23:39
Where does `settings.json` mean to sit, @mkoura?

I think I agree with @Shougo though. If placeholders are not navigable from within the insert mode they're not very effcient. It's faster to type your arguments after the opening parenthesis.

**Comment by nicoe** [comment] 2019-02-20 00:11
@robertsawko It's a LanguageClient configuration file see `:help g:LanguageClient_settingsPath`

**Comment by robertsawko** [comment] 2019-02-25 09:53
Thanks, @nicoe. I can now suppress this.

I think I agree with @Shougo comment. Should we keep this opened? As for me if there was just a way to navigate the parameters it would have been entirely fine, I think. Please let me know.

**Comment by 9ary** [comment] 2019-02-25 10:00
> Should we keep this opened?

If I understand Shougo's comment properly, it seems like LanguageClient is passing the snippet to deoplete incorrectly, so yes.

**Comment by autozimu** [comment] 2019-03-05 18:15
This is caused by the python language server, which is not respecting client declaration of not supporting snippet.

The language server sends completion items of snippet format to this client and this client just pass on to vim or deoplete. That's what happened in this issue.

Please file issue or +1 at python language server repo.

**Closed as completed by autozimu** 2019-03-05 18:15 UTC

**Comment by Shougo** [comment] 2019-03-16 14:44
I have fixed the problem completely in pyls side.
Please test it.

https://github.com/palantir/python-language-server/pull/526
