### ISSUE TITLE
update the tag stack using gettagstack and settagstack when jumping

### ISSUE THREAD

**Issue by iamcodemaker** [autozimu/LanguageClient-neovim#1217] opened 2021-04-14 19:55 UTC
Jumps should update vim's tag stack using `gettagstack()` and `settagstack()` to make going back easier (no idea if this is supported in neovim). You can currently go back using `C-o` but it follows all moves rather than only code navigation related moves. Supporting the tag stack would allow jumping back using `C-t` which works independently from regular moves. Vim's ctag support uses the tag stack.

Support for interacting with the tag stack appears to have been added here: https://github.com/neovim/neovim/pull/9951.

**Comment by martskins** [comment] 2021-04-14 21:16
I think this would be nice to implement. I don't have any immediate plans to implement it though, so anyone who wants to give it a try go ahead, otherwise I'll see if I can find some time to add this eventually.

Having said that, I'm closing this as a duplicate of #517. Feel free to re-open if you don't agree it's a duplicate though.

**Closed as completed by martskins** 2021-04-14 21:16 UTC

**Comment by iamcodemaker** [comment] 2021-04-15 00:26
It's totally a duplicate. I'll take a look and see if I can figure out how to make this work.
