### ISSUE TITLE
Don't enable escape hotkey by default

### ISSUE THREAD

**Issue by stevenroose** [autozimu/LanguageClient-neovim#926] opened 2019-12-19 16:20 UTC
I can't find a way to disable the (horrible, fwiw) map of escape in normal mode to "go to definition".

A simple 
```
nunmap <Esc>
```
at the end of the config doesn't work because languageclient somehow only enables it for languages supported by languageclient.

I'm literally dying over this.

**Comment by martskins** [comment] 2020-07-02 07:01
LanguageClient-neovim sets no mappings at all. In fact there's no occurrences of `ESC` in the whole code base. If you can provide a reproducible minimal vim config for this I'd be interested in helping out, but I definitely don't think this is on LanguageClient.

**Comment by martskins** [comment] 2020-07-02 07:02
(Sorry, didn't want to close, just comment :smile: )

**Comment by martskins** [comment] 2020-07-14 07:40
I'm gonna close this due to lack of answer, but feel free to re-open if you still have questions about this.

**Closed as completed by martskins** 2020-07-14 07:40 UTC
