### ISSUE TITLE
LanguageClientStarted autocmd does not work

### ISSUE THREAD

**Issue by nkakouros** [autozimu/LanguageClient-neovim#992] opened 2020-03-17 19:37 UTC
- Did you upgrade to latest plugin version?
Yes, with vim-plug.

- Did you upgrade to/compile latest binary? Run shell command
  `bin/languageclient --version` to get its version number.
```
languageclient 0.1.156
```

- (Neovim users only) Did you check output of `:checkhealth LanguageClient`?
```
health#LanguageClient#check
========================================================================
  - OK: binary found: /home/nikos/.local/share/nvim/plugged/LanguageClient-neovim/bin/languageclient
  - OK: languageclient 0.1.156
  - OK: Floating window is supported and will be used for hover

```

- Did you check [troubleshooting]?
Yes

[troubleshooting]: https://github.com/autozimu/LanguageClient-neovim/blob/next/INSTALL.md#troubleshooting

## Describe the bug

The `LanguageClientStarted` autocmd does not work.

## Environment

- neovim/vim version (`nvim --version` or `vim --version`): 
```
NVIM v0.5.0-417-g5a5c2f029
Build type: RelWithDebInfo
LuaJIT 2.0.5
Compilation: /usr/bin/cc -march=x86-64 -mtune=generic -O2 -pipe -fno-plt -O2 -g -Og -g -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wshadow -Wconversion -Wmissing-prototypes -Wimplicit-fallthrough -Wvla -fstack-protector-strong -fno-common -fdiagnostics-color=auto -DINCLUDE_GENERATED_DECLARATIONS -D_GNU_SOURCE -DNVIM_MSGPACK_HAS_FLOAT32 -DNVIM_UNIBI_HAS_VAR_FROM -DMIN_LOG_LEVEL=3 -I/tmp/yaourt-tmp-nikos/aur-neovim-git/src/neovim-git/build/config -I/tmp/yaourt-tmp-nikos/aur-neovim-git/src/neovim-git/src -I/usr/include -I/tmp/yaourt-tmp-nikos/aur-neovim-git/src/neovim-git/build/src/nvim/auto -I/tmp/yaourt-tmp-nikos/aur-neovim-git/src/neovim-git/build/include
Compiled by nikos@nikos-laptop

Features: +acl +iconv +tui
See ":help feature-compile"

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/usr/share/nvim"

Run :checkhealth for more info

```

- This plugin version (`git rev-parse --short HEAD`): 7c9c023
- This plugin's binary version (`bin/languageclient --version`): languageclient 0.1.156
- Minimal vimrc content (A minimal vimrc is the smallest vimrc that could
  reproduce the issue. Refer to an example [here][min-vimrc.vim]):

```
call plug#begin('~/.local/share/nvim/plugged')

Plug 'autozimu/LanguageClient-neovim', {
    \ 'branch': 'next',
    \ 'do': 'bash install.sh',
    \ }

call plug#end()

augroup filetype_rust
    autocmd!
    autocmd User LanguageClientStarted echo 'fff'
augroup END
```

- Language server link and version: whichever

[min-vimrc.vim]: https://github.com/autozimu/LanguageClient-neovim/blob/next/min-vimrc.vim

## To Reproduce

1. Open vim and edit a file for which a language server will run.
2. See the message that LC ran.

## Current behavior

The `fff` message is not printed (from the autocmd).

## Expected behavior

I would expect `fff` to be echoed in the message area.

## Additional context

`git bisect` showed that the problem started with commit 13729a41570a2226f98f4eb617c0fa356fd7bf2a

**Comment by martskins** [comment] 2020-10-17 12:49
Is this still an issue for you @nkakouros? I couldn't reproduce this so I assume it was fixed in a later commit.

**Comment by martskins** [comment] 2020-10-20 21:26
Closing this as it's stale and I suspect it was fixed already but feel free to re-open if that's not the case

**Closed as completed by martskins** 2020-10-20 21:26 UTC
