### ISSUE TITLE
LC not detecting and working with Fortran.

### ISSUE THREAD

**Issue by rudrab** [autozimu/LanguageClient-neovim#832] opened 2019-06-07 13:28 UTC
- Did you upgrade to latest plugin version?
`Yes`
- Did you upgrade to/compile latest binary? Run shell command
  `bin/languageclient --version` to get its version number.
```
~/.vim/bundle/LanguageClient-neovim/bin/languageclient --version
languageclient 0.1.146 
```
- (Neovim users only) Did you check output of `:checkhealth LanguageClient`?
- Did you check [troubleshooting]?
Yes
[troubleshooting]: https://github.com/autozimu/LanguageClient-neovim/blob/next/INSTALL.md#6-troubleshooting

## Describe the bug
I am trying it with fortran, with `fortran language server(fortls) `installed using `pip3`. I am expecting it to give completion options for modules etc, defined in the module. 
## Environment
- neovim/vim version (`nvim --version` or `vim --version`):
```
vim --version
VIM - Vi IMproved 8.1 (2018 May 18, compiled May 28 2019 11:36:41)
Included patches: 1-1413
Modified by <bugzilla@redhat.com>
Compiled by <bugzilla@redhat.com>
Huge version without GUI.  Features included (+) or not (-):
```

- This plugin version (`git rev-parse --short HEAD`):
```
git rev-parse --short HEAD
3e31d01
```

- This plugin's binary version (`bin/languageclient --version`):
```
~/.vim/bundle/LanguageClient-neovim/bin/languageclient --version
languageclient 0.1.146 
```
- Minimal vimrc content (A minimal vimrc is the smallest vimrc that could
  reproduce the issue. Refer to an example [here][min-vimrc.vim]):
```
set nu
if empty(glob('~/.vim/autoload/plug.vim'))
	  silent !curl -fLo ~/.vim/autoload/plug.vim --create-dirs
	          \ https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
	    autocmd VimEnter * PlugInstall --sync | source $MYVIMRC
    endif
    
call plug#begin('~/.vim/bundle/')
Plug 'autozimu/LanguageClient-neovim', {
			\'branch': 'next', 
			\'do': 'bash install.sh', 
			\}

call plug#end()

augroup filetype_f90
    autocmd!
    autocmd BufReadPost *.f90 setlocal filetype=fortran
augroup END

" Always draw sign column. Prevent buffer moving when adding/deleting sign.
set signcolumn=yes

let g:LanguageClient_serverCommands = { 
			\'fortran': ['/usr/local/bin/fortls', '--notify_init', '--incrmental_sync', '--autocomplete_no_prefix'], 
			\}
"let $RUST_BACKTRACE = 1
let g:LanguageClient_loggingLevel = 'INFO'
let g:LanguageClient_loggingFile =  expand('/tmp/LanguageClient.log')
let g:LanguageClient_serverStderr = expand('/tmp/LanguageServer.log')

```
- Language server link and version:
https://github.com/hansec/fortran-language-server

## To Reproduce

1. NB. Fortran is not in sample, So, I am adding a simple hello_world.f90
```
        Program Hello
                use iso  ! Expecting to get option of iso_fortran_env
                write(*,*) "Hello"
        End Program Hello
```
As I said, I am expecting it to show completion option, but there is absolutely nothing.
## Current behavior
No completion option appears
## Expected behavior
It should give the completion options defined in fortls

LanguageClient.log
https://paste.fedoraproject.org/paste/31Gus3scjYT8eI711dZnaw 

LanguageServer.log says: `Change request failed for unknown file "/home/rudra/hello_world.f90"`

**Comment by MagBad** [comment] 2019-06-10 09:59
Hi,

I'm trying to reproduce your bug and I'm getting the same no completion. However, both my and your
```LanguageClient.log``` contain: ``` Module "iso" not found in project```. 
Running the same file inside vscode works without a problem. But in both cases I only get the Keyword suggestion completion.

Maybe there is a issue regarding fortls?

Best regards
Magnus

**Comment by hansec** [comment] 2019-07-08 16:03
@rudrab Sorry, I guess I didn't look at this issue earlier. Can you repost the log? It looks like it expired.

Based on the error I think perhaps the plugin is trying to send a change request for a file before it is registered with the language server (via an open/save request or being present in the root folder at launch). In this case the language server just ignores it and reports an error since it hasn't been tracking the file so it doesn't know what the change is relative to.

**Comment by rudrab** [comment] 2019-07-09 05:04
@hansec : I closed this issue, because I moved from LC to `coc.nvim`. And yes, in coc, too, I am getting this error: **Change request failed for unknown file "/home/rudra/i.f90"**

**Comment by martskins** [comment] 2020-12-16 02:33
Closing as it seems to be a server issue as per your last comment.

**Closed as completed by martskins** 2020-12-16 02:33 UTC
